"""Starmap data + rendering. Reads the precursor-era stars.json and draws stars.

The data lives in src/scz/content/universe/stars.json (generated by
tools/extract_sc2_universe.py from the UQM source). Each star has a
position, type (DWARF/GIANT/SUPER_GIANT), color, and optional lore tag
(defined_name) that drives any special rendering.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Callable

import pygame


# UQM color names → RGB. Loose interpretation; we can tune later.
STAR_COLOR_RGB: dict[str, tuple[int, int, int]] = {
    "BLUE_BODY":   (120, 160, 255),
    "WHITE_BODY":  (240, 240, 255),
    "YELLOW_BODY": (255, 230, 120),
    "GREEN_BODY":  (140, 255, 160),
    "ORANGE_BODY": (255, 180, 100),
    "RED_BODY":    (255, 110, 100),
}

STAR_TYPE_RADIUS: dict[str, int] = {
    "DWARF_STAR": 2,
    "GIANT_STAR": 4,
    "SUPER_GIANT_STAR": 7,
}

# Universe coordinate range. Anything beyond this is QuasiSpace or invalid.
UNIVERSE_MAX = 10000.0


# Type alias for the universe→screen transform function
TransformFn = Callable[[float, float], tuple[float, float]]


class Starmap:
    """Loads and renders the precursor-era star data."""

    def __init__(self, json_path: Path) -> None:
        text = json_path.read_text(encoding="utf-8")
        data = json.loads(text)
        self.stars: list[dict] = data["stars"]
        self.metadata: dict = data.get("metadata", {})

        # Pre-filter Rainbow-being-seeded stars for special rendering
        self.rainbow_stars: list[dict] = [
            s for s in self.stars if s.get("defined_name") == "RAINBOW_BEING_SEEDED"
        ]

    def render(self, surface: pygame.Surface, transform: TransformFn) -> None:
        """Draw all stars onto the surface using the transform."""
        for star in self.stars:
            x, y = transform(star["x"], star["y"])
            ix, iy = int(x), int(y)
            radius = STAR_TYPE_RADIUS.get(star["type"], 2)
            color = STAR_COLOR_RGB.get(star["color"], (200, 200, 200))

            # Glow halo for giants and supergiants
            if star["type"] == "SUPER_GIANT_STAR":
                halo = (color[0] // 4, color[1] // 4, color[2] // 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 6, 1)
            elif star["type"] == "GIANT_STAR":
                halo = (color[0] // 4, color[1] // 4, color[2] // 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 2)

            pygame.draw.circle(surface, color, (ix, iy), radius)

        # Rainbow Worlds get a special ringed render (the orbiting drone ring)
        for star in self.rainbow_stars:
            x, y = transform(star["x"], star["y"])
            ix, iy = int(x), int(y)
            # Rotating chromatic ring — for now, a multi-color ring approximation
            ring_radius = 8
            colors = [
                (255, 100, 100), (255, 180, 100), (255, 230, 120),
                (140, 255, 160), (120, 200, 255), (180, 130, 255),
            ]
            for i, c in enumerate(colors):
                angle_pct = i / len(colors)
                # Just draw a small dot at each angle around the star
                import math
                a = angle_pct * 2 * math.pi
                rx = ix + int(ring_radius * math.cos(a))
                ry = iy + int(ring_radius * math.sin(a))
                pygame.draw.circle(surface, c, (rx, ry), 1)

    def find_nearest_star(
        self, ux: float, uy: float, max_distance: float = 200.0
    ) -> dict | None:
        """Return the nearest star within max_distance universe units, or None."""
        best = None
        best_d2 = max_distance * max_distance
        for star in self.stars:
            dx = star["x"] - ux
            dy = star["y"] - uy
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = star
        return best
