"""Starmap data + rendering. Reads the precursor-era stars.json and draws stars.

The data lives in src/scz/content/universe/stars.json (generated by
tools/extract_sc2_universe.py from the UQM source). Each star has a
position, type (DWARF/GIANT/SUPER_GIANT), color, and optional lore tag
(defined_name) that drives any special rendering.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Callable

import pygame

if TYPE_CHECKING:
    from scz.engine.game import Game


# UQM color names → RGB. Loose interpretation; we can tune later.
STAR_COLOR_RGB: dict[str, tuple[int, int, int]] = {
    "BLUE_BODY":   (120, 160, 255),
    "WHITE_BODY":  (240, 240, 255),
    "YELLOW_BODY": (255, 230, 120),
    "GREEN_BODY":  (140, 255, 160),
    "ORANGE_BODY": (255, 180, 100),
    "RED_BODY":    (255, 110, 100),
}

STAR_TYPE_RADIUS: dict[str, int] = {
    "DWARF_STAR": 2,
    "GIANT_STAR": 4,
    "SUPER_GIANT_STAR": 7,
}

# Universe coordinate range. Anything beyond this is QuasiSpace or invalid.
UNIVERSE_MAX = 10000.0


# --- Label visibility tiers ---
# Like real-world digital maps: big landmarks show from far out, small ones
# only when you zoom in close. Tuned by star type. Lore-tagged stars (Sol,
# Slylandro home, etc.) show one tier earlier so plot-critical destinations
# remain findable. Rainbow Worlds always show because they're the central
# plot artifacts and the player will be hunting for them.
LABEL_MIN_ZOOM_BY_TYPE: dict[str, float] = {
    "SUPER_GIANT_STAR": 0.8,   # ~always visible (galaxy view shows them all)
    "GIANT_STAR": 2.5,         # mid-zoom
    "DWARF_STAR": 7.0,         # close zoom only
}
LABEL_MIN_ZOOM_LORE_TAGGED: dict[str, float] = {
    "SUPER_GIANT_STAR": 0.8,
    "GIANT_STAR": 0.8,
    "DWARF_STAR": 2.5,         # one tier earlier than untagged dwarfs
}
LABEL_MIN_ZOOM_RAINBOW: float = 0.8   # always visible — plot-critical

# Per-dim-tier brightness multipliers applied at render time. Tier 0 is
# untouched (full brightness); tier 1 is visited-but-still-worth-revisiting
# (slight dim); tier 2 is fully-drained-and-explored (very dim — barely
# a marker). See `system_scan.system_dim_tier` for the tier-assignment
# rules.
DIM_FACTOR_BY_TIER: dict[int, float] = {
    0: 1.0,
    1: 0.55,
    2: 0.22,
}


# Subtle tints applied to label text so each star color reads slightly
# different. Mixed with off-white for legibility.
LABEL_COLOR_BY_STAR: dict[str, tuple[int, int, int]] = {
    "BLUE_BODY":   (200, 220, 255),
    "WHITE_BODY":  (230, 230, 240),
    "YELLOW_BODY": (245, 235, 200),
    "GREEN_BODY":  (210, 240, 215),
    "ORANGE_BODY": (245, 220, 190),
    "RED_BODY":    (245, 205, 200),
}


# Type alias for the universe→screen transform function
TransformFn = Callable[[float, float], tuple[float, float]]


class Starmap:
    """Loads and renders the precursor-era star data."""

    def __init__(self, json_path: Path) -> None:
        text = json_path.read_text(encoding="utf-8")
        data = json.loads(text)
        self.stars: list[dict] = data["stars"]
        self.metadata: dict = data.get("metadata", {})

        # Synthetic stars — known systems that aren't in the original SC2
        # starmap because they don't exist in SC2's era. Mh-Lai is the
        # Furling home; canon says the Furlings unmake it at Migration's
        # end, so SC2 archaeologists find no trace — but in OUR era it is
        # very much there and visible. Arilou Outpost is the Sage's seat.
        from scz.content.arilou_outpost import arilou_outpost_star
        from scz.content.home_system import home_star
        from scz.content.taalos_stone_system import taalos_stone_star
        self.stars.append(home_star())
        self.stars.append(arilou_outpost_star())
        self.stars.append(taalos_stone_star())

        # Pre-filter Rainbow-being-seeded stars for special rendering
        self.rainbow_stars: list[dict] = [
            s for s in self.stars if s.get("defined_name") == "RAINBOW_BEING_SEEDED"
        ]

    def render(
        self,
        surface: pygame.Surface,
        transform: TransformFn,
        game: "Game | None" = None,
    ) -> None:
        """Draw all stars onto the surface using the transform.

        When `game` is supplied, each star's color is dimmed by its
        `system_dim_tier` — visited systems render slightly dimmer;
        drained-and-fully-explored systems render very dim. Without
        `game`, all stars render at full brightness (back-compat).
        """
        # Lazy import — keeps starmap.py free of the system_scan circular
        # dependency when no game is supplied.
        if game is not None:
            from scz.content.system_scan import system_dim_tier
        for star in self.stars:
            x, y = transform(star["x"], star["y"])
            ix, iy = int(x), int(y)
            radius = STAR_TYPE_RADIUS.get(star["type"], 2)
            color = STAR_COLOR_RGB.get(star["color"], (200, 200, 200))

            # Apply visit / depletion dimming. Tier 0 is a no-op (factor
            # 1.0); tiers 1/2 scale all color channels uniformly.
            if game is not None:
                tier = system_dim_tier(game, star)
                factor = DIM_FACTOR_BY_TIER.get(tier, 1.0)
                if factor < 1.0:
                    color = (
                        int(color[0] * factor),
                        int(color[1] * factor),
                        int(color[2] * factor),
                    )

            # Glow halo for giants and supergiants
            if star["type"] == "SUPER_GIANT_STAR":
                halo = (color[0] // 4, color[1] // 4, color[2] // 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 6, 1)
            elif star["type"] == "GIANT_STAR":
                halo = (color[0] // 4, color[1] // 4, color[2] // 4)
                pygame.draw.circle(surface, halo, (ix, iy), radius + 2)

            pygame.draw.circle(surface, color, (ix, iy), radius)

        # Rainbow Worlds get a special ringed render (the orbiting drone ring)
        for star in self.rainbow_stars:
            x, y = transform(star["x"], star["y"])
            ix, iy = int(x), int(y)
            # Rotating chromatic ring — for now, a multi-color ring approximation
            ring_radius = 8
            colors = [
                (255, 100, 100), (255, 180, 100), (255, 230, 120),
                (140, 255, 160), (120, 200, 255), (180, 130, 255),
            ]
            for i, c in enumerate(colors):
                angle_pct = i / len(colors)
                # Just draw a small dot at each angle around the star
                import math
                a = angle_pct * 2 * math.pi
                rx = ix + int(ring_radius * math.cos(a))
                ry = iy + int(ring_radius * math.sin(a))
                pygame.draw.circle(surface, c, (rx, ry), 1)

    def render_labels(
        self,
        surface: pygame.Surface,
        transform: TransformFn,
        zoom: float,
        font: pygame.font.Font,
    ) -> None:
        """Draw star-name labels next to stars whose visibility tier the
        current zoom level reaches. Call after render() so labels sit on
        top of star sprites.
        """
        # Pre-resolve per-star threshold to avoid dict lookups in the loop
        for star in self.stars:
            name = star.get("cluster_name")
            if not name:
                continue

            defined = star.get("defined_name")
            star_type = star.get("type", "DWARF_STAR")

            # Decide visibility threshold
            if defined == "RAINBOW_BEING_SEEDED":
                threshold = LABEL_MIN_ZOOM_RAINBOW
            elif defined:
                threshold = LABEL_MIN_ZOOM_LORE_TAGGED.get(star_type, 5.0)
            else:
                threshold = LABEL_MIN_ZOOM_BY_TYPE.get(star_type, 5.0)

            if zoom < threshold:
                continue

            sx, sy = transform(star["x"], star["y"])
            # Cheap on-screen test — skip labels well outside the surface
            sw, sh = surface.get_size()
            if sx < -100 or sx > sw + 100 or sy < -50 or sy > sh + 50:
                continue

            color = LABEL_COLOR_BY_STAR.get(star.get("color"), (220, 220, 230))
            text = font.render(name, True, color)
            # Subtle shadow so the label reads against bright stars or
            # nebulous backgrounds we may add later.
            shadow = font.render(name, True, (10, 10, 20))
            radius = STAR_TYPE_RADIUS.get(star_type, 2)
            ox = int(sx) + radius + 6
            oy = int(sy) - text.get_height() // 2
            surface.blit(shadow, (ox + 1, oy + 1))
            surface.blit(text, (ox, oy))

    def find_nearest_star(
        self, ux: float, uy: float, max_distance: float = 200.0
    ) -> dict | None:
        """Return the nearest star within max_distance universe units, or None."""
        best = None
        best_d2 = max_distance * max_distance
        for star in self.stars:
            dx = star["x"] - ux
            dy = star["y"] - uy
            d2 = dx * dx + dy * dy
            if d2 < best_d2:
                best_d2 = d2
                best = star
        return best
