"""MeleeCombatScene — 1v1 ship combat with Newtonian movement.

Both sides AI-controlled by default (the auto-fight commitment). The
test harness uses this to drive Super Melee fights to completion. A
player-control path will land later; the engine treats it as just
another action source feeding the same physics + weapons code.

Slice scope per the design canon:
- 2D top-down, screen-wrapping arena
- Newtonian momentum (velocity persists; thrust adds to it)
- Projectile primary weapons (no specials yet — those land in pass 2)
- Hull + regenerating shield (shields only on Furling-faction ships)
- Win = one ship's hull hits 0; the surviving side is the winner

When the fight ends the scene calls `on_finish(winner_side)` if provided,
else falls back to set_scene(SuperMeleeScene). The win callback is what
the SuperMelee picker uses to advance to a result screen.
"""

from __future__ import annotations

import math
import os
import random
from dataclasses import dataclass, field
from typing import Callable

import pygame

from scz.combat.ai import AIAction, decide
from scz.combat.ships import ShipClass
from scz.engine.scene import Scene


# Arena dimensions in world units — wraps at edges.
ARENA_W = 1600.0
ARENA_H = 1000.0

# Alpha-cutout ship sprite directory + per-ship-id filename map.
# Generated by tools/generate_ship_sprites.py from approved Firefly hero
# images. When a sprite is missing we fall back to the procedural polygon
# silhouette in _draw_ship — the existing code remains the safety net.
SHIP_SPRITE_DIR = os.path.join(
    "assets", "ships", "sprites",
)
SHIP_SPRITES: dict[str, str] = {
    "furling_scout":     "ship_furling_scout.png",
    "persuader_vessel":  "ship_persuader_vessel.png",
    "arilou_skiff":      "ship_arilou_skiff.png",
    "androsynth_cruiser":"ship_androsynth_cruiser.png",
    "burv_broadcaster":  "ship_burv_broadcaster.png",
    "cleanser_cruiser":  "ship_cleanser_cruiser.png",
    "compeller_vessel":  "ship_compeller_vessel.png",
    "melnorme_trader":   "ship_melnorme_trader.png",
    "defender_vessel":   "ship_defender_vessel.png",
    "lemmkin_skitter":   "ship_lemmkin_skitter.png",
    "mmrnmhrm_sentinel": "ship_mmrnmhrm_sentinel.png",
    "mycon_podship":     "ship_mycon_podship.png",
    "proto_ur_quan":     "ship_proto_urquan.png",
    "proto_qor_ah":      "ship_proto_qor_ah.png",
    "sentry_drone_47t":  "ship_sentry_drone_47t.png",
    "thinn_blade":       "ship_thinn_blade.png",
    "utwig_jugger":      "ship_utwig_jugger.png",
}
# Nominal sprite size in world units along the longest axis. Tuned so a
# sprite reads about the same size as the legacy polygon at typical
# viewport scale (~0.7 → ~36px on screen).
SHIP_SPRITE_BASE_SIZE = 56

# Per-ship projectile sprites live in the same dir keyed by ship_id —
# `projectile_<ship_id>.png`. Missing files fall back to the legacy
# colored-circle rendering. Authored as glowing FX on black background;
# tools/extract_projectile_alpha.py produces luma-alpha PNGs that
# composite correctly over the game's black play area.
PROJECTILE_SPRITE_BASE_SIZE = 28

# Projectile pool cap (slice — we won't approach this)
MAX_PROJECTILES = 200

# How long after fight-end before the scene auto-exits
FIGHT_END_DWELL = 2.5

# Damage smear constant — when shields take damage they refill more
# slowly while damage continues. We do this by resetting the regen
# cooldown each tick of damage taken.
SHIELD_HIT_REGEN_DELAY_RESET = True


@dataclass
class ShipState:
    """Runtime state of one ship in combat. The ShipClass is the read-only
    spec; this is the mutable counterpart.
    """
    cls: ShipClass
    side: str
    x: float
    y: float
    heading: float
    vx: float = 0.0
    vy: float = 0.0
    hull: float = 0.0
    shield: float = 0.0
    # One-shot SFX flags so the alert chimes fire on threshold crossing,
    # not every damage tick. Reset implicit-True (default False); set to
    # True the first time the threshold is crossed downward.
    alert_warning_fired: bool = False   # shield dropped < 25%
    alert_danger_fired: bool = False    # hull dropped < 25%
    energy: float = 0.0
    shield_regen_cooldown: float = 0.0
    primary_cooldown: float = 0.0
    alive: bool = True
    hit_flash: float = 0.0     # render flash on damage

    @classmethod
    def spawn(cls, ship_cls: ShipClass, x: float, y: float, heading: float) -> "ShipState":
        return cls(
            cls=ship_cls,
            side=ship_cls.side,
            x=x, y=y, heading=heading,
            hull=ship_cls.hull_max,
            shield=ship_cls.shield_max,
            energy=ship_cls.energy_max,
        )

    def apply_damage(self, amount: float) -> None:
        """Apply incoming damage. Shields absorb first, then hull."""
        if amount <= 0 or not self.alive:
            return
        self.hit_flash = 0.25
        if self.shield > 0:
            absorbed = min(self.shield, amount)
            self.shield -= absorbed
            amount -= absorbed
            if SHIELD_HIT_REGEN_DELAY_RESET:
                self.shield_regen_cooldown = self.cls.shield_regen_delay
        if amount > 0:
            self.hull -= amount
            if self.hull <= 0:
                self.hull = 0
                self.alive = False


@dataclass
class Projectile:
    x: float
    y: float
    vx: float
    vy: float
    damage: float
    range_left: float   # max distance before despawn
    owner_side: str
    color: tuple[int, int, int]
    owner_ship_id: str = ""   # used to look up projectile_<id>.png sprite
    radius: float = 3.0


@dataclass
class ImpactFx:
    """Short-lived blast-puff at the point a projectile hit a ship.
    Tracked + rendered each frame, retired when t > duration.
    """
    x: float
    y: float
    t: float = 0.0
    duration: float = 0.35
    color: tuple[int, int, int] = (255, 200, 120)
    max_radius: float = 22.0


@dataclass
class DeathFx:
    """Ship-destruction animation: ring shockwave + colored debris
    radiating outward. Plays at the ship's last position for ~1.2 sec
    before the wreck-stub render takes over.
    """
    x: float
    y: float
    color: tuple[int, int, int]
    t: float = 0.0
    duration: float = 1.1
    # Per-debris seed so the particle pattern is deterministic per fx.
    seed: int = 0


@dataclass
class CombatResult:
    winner_side: str | None
    winner_ship: ShipClass | None
    loser_ship: ShipClass | None
    duration: float
    timed_out: bool


class MeleeCombatScene(Scene):
    """1v1 ship combat. Both ships AI-driven by default."""

    # Default to low-risk; runtime can swap to combat_high / combat_boss
    # when those tracks land + when the combat AI flags stakes.
    music_context = "combat_low"  # assets/music/combat_low/

    def __init__(
        self,
        precursor_ship: ShipClass,
        homesteader_ship: ShipClass,
        max_duration: float = 60.0,
        on_finish: Callable[[CombatResult], None] | None = None,
        seed: int | None = None,
        planet_id: str | None = None,
    ) -> None:
        super().__init__()
        self.max_duration = max_duration
        self.on_finish = on_finish
        # When combat is happening "near planet X", pass the planet's
        # id so the combat backdrop shows the same rotating sphere as
        # the orbit/system views did. Visual continuity across the
        # transition.
        self.planet_id = planet_id
        # A per-fight RNG so spawns aren't pixel-perfect identical each
        # run — Aaron specifically wants "somewhat but not perfectly
        # predictable" outcomes. The seed comes from the wall clock if
        # not provided.
        self.rng = random.Random(seed) if seed is not None else random.Random()

        # Spawn at opposite ends, facing each other, with a little jitter
        margin = 200.0
        spread_y = 200.0
        p_y = ARENA_H / 2 + self.rng.uniform(-spread_y, spread_y)
        h_y = ARENA_H / 2 + self.rng.uniform(-spread_y, spread_y)
        self.precursor = ShipState.spawn(
            precursor_ship, margin, p_y, heading=math.pi / 2  # facing +x
        )
        self.homesteader = ShipState.spawn(
            homesteader_ship, ARENA_W - margin, h_y, heading=-math.pi / 2  # facing -x
        )

        self.projectiles: list[Projectile] = []
        self.impact_fx: list[ImpactFx] = []
        self.death_fx: list[DeathFx] = []
        # Tracks which ships we've already spawned a death FX for, so
        # we don't double-spawn when both projectile + cleanup paths
        # observe the alive=False transition.
        self._death_fx_spawned: set[str] = set()

        # Scene-time
        self.time_in_scene: float = 0.0
        self.result: CombatResult | None = None
        self.time_since_result: float = 0.0

        # Set in on_enter
        self.font: pygame.font.Font | None = None
        self.big_font: pygame.font.Font | None = None
        self.screen_w: int = 0
        self.screen_h: int = 0

        # Asteroid field — irregular rocks tumbling in the arena as
        # backdrop decoration. Sprites at assets/asteroids/asteroid_*.png.
        from scz.content.asteroid_field import AsteroidField
        self.asteroids = AsteroidField(seed=seed).spawn(
            arena_w=ARENA_W, arena_h=ARENA_H, count=6,
            min_size=40.0, max_size=110.0,
            clear_margin=300.0,
        )

    # ------------------------------------------------------------------
    # Scene API
    # ------------------------------------------------------------------

    def on_enter(self) -> None:
        assert self.game is not None
        self.screen_w, self.screen_h = self.game.screen.get_size()
        self.font = pygame.font.SysFont("consolas", 18)
        self.big_font = pygame.font.SysFont("consolas", 36, bold=True)
        # Sprite cache keyed by ship.cls.id. None = sprite missing / failed.
        self._ship_sprite_cache: dict[str, pygame.Surface | None] = {}
        self._projectile_sprite_cache: dict[str, pygame.Surface | None] = {}
        # Starfield backdrop — `None` until first draw load attempt;
        # `False` means we tried and the PNG was missing (don't retry).
        self._starfield_sprite: pygame.Surface | None | bool = None
        self._starfield_scaled: tuple[pygame.Surface, tuple[int, int]] | None = None

    def snapshot(self) -> dict | None:
        # Combat is intentionally NOT rewindable — committing to a fight
        # is committing. Time Drive rewinds you to BEFORE the combat
        # started, not partway through.
        return None

    def update(self, dt: float, inp) -> None:  # type: ignore[no-untyped-def]
        self.time_in_scene += dt

        if self.result is not None:
            # Fight is over — dwell briefly, then finish.
            self.time_since_result += dt
            if self.time_since_result >= FIGHT_END_DWELL:
                self._finish()
            return

        # --- Per-ship update ---
        for me, other in (
            (self.precursor, self.homesteader),
            (self.homesteader, self.precursor),
        ):
            if not me.alive:
                continue
            action = decide(me, other)
            self._apply_action(me, action, dt)
            self._integrate(me, dt)
            self._regen(me, dt)
            if action.fire_primary:
                self._fire_primary(me)
            if me.hit_flash > 0:
                me.hit_flash = max(0.0, me.hit_flash - dt)

        # --- Projectiles ---
        self._update_projectiles(dt)

        # --- Asteroid field (visual only — drifts and tumbles) ---
        self.asteroids.update(dt, ARENA_W, ARENA_H)

        # --- Combat FX ---
        for fx in self.impact_fx:
            fx.t += dt
        self.impact_fx = [fx for fx in self.impact_fx if fx.t < fx.duration]
        for fx in self.death_fx:
            fx.t += dt
        self.death_fx = [fx for fx in self.death_fx if fx.t < fx.duration]

        # --- Win detection ---
        if not self.precursor.alive and self.homesteader.alive:
            self._record_result(self.homesteader, self.precursor)
        elif not self.homesteader.alive and self.precursor.alive:
            self._record_result(self.precursor, self.homesteader)
        elif not self.precursor.alive and not self.homesteader.alive:
            # Double-KO. Call it a draw by treating Precursor as not winning.
            self._record_result(None, None)
        elif self.time_in_scene >= self.max_duration:
            # Timeout — whoever has more total HP wins, ties go to Precursor
            p_score = self.precursor.hull + self.precursor.shield
            h_score = self.homesteader.hull + self.homesteader.shield
            if p_score >= h_score:
                self._record_result(self.precursor, self.homesteader, timed_out=True)
            else:
                self._record_result(self.homesteader, self.precursor, timed_out=True)

    def render(self, screen: pygame.Surface) -> None:
        screen.fill((4, 4, 14))

        # Arena boundary (wraps but we draw it as a faint frame)
        scale = self._scale()
        ox = (self.screen_w - ARENA_W * scale) / 2
        oy = (self.screen_h - ARENA_H * scale) / 2
        pygame.draw.rect(
            screen, (28, 28, 48),
            (ox, oy, ARENA_W * scale, ARENA_H * scale),
            1,
        )

        # Starfield backdrop — painted PNG (atmospheric deep space with
        # hero stars + nebula tint) if available, else the procedural
        # 180-dot fallback. PNG lives at assets/combat/starfield.png and
        # is loaded lazily on first draw.
        starfield = self._load_starfield_sprite()
        if starfield is not None:
            target_w = int(ARENA_W * scale)
            target_h = int(ARENA_H * scale)
            sw, sh = starfield.get_size()
            if (sw, sh) != (target_w, target_h):
                starfield = pygame.transform.smoothscale(starfield, (target_w, target_h))
                self._starfield_scaled = (starfield, (target_w, target_h))
            screen.blit(starfield, (ox, oy))
        else:
            rng = random.Random(101)
            for _ in range(180):
                sx = ox + rng.uniform(0, ARENA_W * scale)
                sy = oy + rng.uniform(0, ARENA_H * scale)
                b = rng.randint(60, 200)
                pygame.draw.circle(screen, (b // 2, b // 2, b), (int(sx), int(sy)), 1)

        # Asteroid field — irregular tumbling rocks behind the ships
        self.asteroids.draw(screen, ox, oy, scale, self._world_to_screen)

        # Planet backdrop — same rotating sphere as the orbit/system
        # views, anchored in a corner so it doesn't dominate the arena.
        # Time-synced via self.time_in_scene so rotation continues
        # smoothly across the system->combat transition.
        if self.planet_id:
            from scz.content.planet_sphere import has_sphere, get_frame
            if has_sphere(self.planet_id):
                planet_diam = max(180, int(min(self.screen_w, self.screen_h) * 0.32))
                surf = get_frame(self.planet_id, self.time_in_scene, diameter=planet_diam)
                if surf is not None:
                    # Anchor in the upper-right corner of the viewport.
                    pad = 24
                    px = self.screen_w - planet_diam - pad
                    py = pad
                    screen.blit(surf, (px, py))

        # Projectiles
        for p in self.projectiles:
            sx, sy = self._world_to_screen(p.x, p.y, ox, oy, scale)
            sprite = self._load_projectile_sprite(p.owner_ship_id) if p.owner_ship_id else None
            if sprite is not None:
                # rotate to match velocity direction (sprite authored nose-up)
                heading = math.atan2(p.vx, -p.vy)
                angle_deg = -math.degrees(heading)
                rotated = pygame.transform.rotozoom(sprite, angle_deg, scale)
                rect = rotated.get_rect(center=(int(sx), int(sy)))
                screen.blit(rotated, rect)
            else:
                pygame.draw.circle(screen, p.color, (int(sx), int(sy)), max(2, int(p.radius * scale)))

        # Ships
        for ship in (self.precursor, self.homesteader):
            self._draw_ship(screen, ship, ox, oy, scale)

        # Combat FX — impact blast-puffs + ship-death explosions.
        # Drawn AFTER ships so they overlay; impacts fade fast, death
        # FX is a longer expanding-ring + colored debris animation.
        for fx in self.impact_fx:
            self._draw_impact_fx(screen, fx, ox, oy, scale)
        for fx in self.death_fx:
            self._draw_death_fx(screen, fx, ox, oy, scale)

        # HUDs (one per side)
        self._draw_hud(screen)

        # Big result overlay
        if self.result is not None and self.big_font is not None:
            text_winner = self._result_text()
            label = self.big_font.render(text_winner, True, (255, 230, 180))
            lw, lh = label.get_size()
            box = pygame.Surface((lw + 80, lh + 60), pygame.SRCALPHA)
            box.fill((10, 10, 30, 220))
            screen.blit(box, ((self.screen_w - lw - 80) // 2, (self.screen_h - lh - 60) // 2))
            screen.blit(label, ((self.screen_w - lw) // 2, (self.screen_h - lh) // 2))

    # ------------------------------------------------------------------
    # Physics + actions
    # ------------------------------------------------------------------

    def _apply_action(self, ship: ShipState, action: AIAction, dt: float) -> None:
        cls = ship.cls
        # Rotation
        if action.turn_dir != 0:
            ship.heading += action.turn_dir * cls.turn_rate * dt
            ship.heading = (ship.heading + math.pi) % (2 * math.pi) - math.pi
        # Thrust
        if action.thrust:
            fx = math.sin(ship.heading) * cls.acceleration * dt
            fy = -math.cos(ship.heading) * cls.acceleration * dt
            ship.vx += fx
            ship.vy += fy
            speed = math.hypot(ship.vx, ship.vy)
            if speed > cls.top_speed:
                # Cap
                ship.vx *= cls.top_speed / speed
                ship.vy *= cls.top_speed / speed
        # Primary cooldown decrement (independent of fire decision)
        if ship.primary_cooldown > 0:
            ship.primary_cooldown = max(0.0, ship.primary_cooldown - dt)

    def _integrate(self, ship: ShipState, dt: float) -> None:
        ship.x += ship.vx * dt
        ship.y += ship.vy * dt
        # Arena wrap
        ship.x %= ARENA_W
        ship.y %= ARENA_H

    def _regen(self, ship: ShipState, dt: float) -> None:
        cls = ship.cls
        if ship.shield_regen_cooldown > 0:
            ship.shield_regen_cooldown = max(0.0, ship.shield_regen_cooldown - dt)
        elif ship.shield < cls.shield_max:
            ship.shield = min(cls.shield_max, ship.shield + cls.shield_regen * dt)
        if ship.energy < cls.energy_max:
            ship.energy = min(cls.energy_max, ship.energy + cls.energy_regen * dt)

    def _fire_primary(self, ship: ShipState) -> None:
        cls = ship.cls
        if ship.energy < cls.primary_energy:
            return
        ship.energy -= cls.primary_energy
        ship.primary_cooldown = 1.0 / max(0.5, cls.primary_rate)
        # Spawn projectile from the ship's nose
        nose_offset = 16.0
        sx = ship.x + math.sin(ship.heading) * nose_offset
        sy = ship.y - math.cos(ship.heading) * nose_offset
        vx = math.sin(ship.heading) * cls.primary_speed
        vy = -math.cos(ship.heading) * cls.primary_speed
        # Projectiles inherit a fraction of the ship's velocity (looks
        # right + gives faster ships subtle aim leading help)
        vx += ship.vx * 0.3
        vy += ship.vy * 0.3
        if len(self.projectiles) < MAX_PROJECTILES:
            self.projectiles.append(Projectile(
                x=sx, y=sy, vx=vx, vy=vy,
                damage=cls.primary_damage,
                range_left=cls.primary_range,
                owner_side=ship.side,
                color=cls.primary_color,
                owner_ship_id=cls.id,
            ))
            # Muzzle flash — small bright puff at the firing point, tinted
            # to the ship's primary_color. Reuses ImpactFx with tighter
            # params so the visual style stays unified with impact bursts.
            self.impact_fx.append(ImpactFx(
                x=sx, y=sy,
                color=cls.primary_color,
                max_radius=9.0,
                duration=0.10,
            ))
            # SFX hook: play this ship's primary_fire.wav from the
            # assets/sfx/ships/<ship_id>/ directory the SFX-gen pipeline
            # wrote. If the asset isn't there yet the SfxBus logs once
            # and stays silent on subsequent hits.
            if self.game is not None and hasattr(self.game, "sfx"):
                self.game.sfx.play(f"ships/{cls.id}/primary_fire")

    def _update_projectiles(self, dt: float) -> None:
        survivors: list[Projectile] = []
        for p in self.projectiles:
            speed = math.hypot(p.vx, p.vy)
            step = speed * dt
            if step > p.range_left:
                continue
            p.x = (p.x + p.vx * dt) % ARENA_W
            p.y = (p.y + p.vy * dt) % ARENA_H
            p.range_left -= step

            # Check hits against the *other* side's ship
            for target in (self.precursor, self.homesteader):
                if not target.alive:
                    continue
                if target.side == p.owner_side:
                    continue
                # Account for arena wrap — check against the toroidal-nearest copy
                dx = self._wrap_delta(p.x, target.x, ARENA_W)
                dy = self._wrap_delta(p.y, target.y, ARENA_H)
                d = math.hypot(dx, dy)
                hit_radius = 18.0 + p.radius
                if d <= hit_radius:
                    target.apply_damage(p.damage)
                    # Spawn an impact FX at the projectile's position.
                    # Bigger damage = bigger puff.
                    self.impact_fx.append(ImpactFx(
                        x=p.x, y=p.y,
                        color=p.color,
                        max_radius=14.0 + min(28.0, p.damage * 1.2),
                        duration=0.25 + min(0.30, p.damage * 0.012),
                    ))
                    # SFX hook: play this projectile's owner-ship's
                    # primary_impact.wav when it hits the target.
                    if self.game is not None and hasattr(self.game, "sfx"):
                        # owner_side lookup -> ship cls -> id
                        shooter = (self.precursor if p.owner_side == self.precursor.side
                                   else self.homesteader)
                        self.game.sfx.play(f"ships/{shooter.cls.id}/primary_impact")
                    # Alert SFX on damage-threshold crossings (once each
                    # per ship per fight). Warning fires on shields below
                    # 25%; danger fires on hull below 25%. Both ships
                    # trigger — the audible cue is "someone's in trouble"
                    # rather than player-vs-AI specific.
                    if self.game is not None and hasattr(self.game, "sfx"):
                        s_max = max(1.0, target.cls.shield_max)
                        h_max = max(1.0, target.cls.hull_max)
                        if (not target.alert_warning_fired
                                and target.shield / s_max < 0.25):
                            target.alert_warning_fired = True
                            self.game.sfx.play("ui/alert_warning")
                        if (not target.alert_danger_fired
                                and target.hull / h_max < 0.25):
                            target.alert_danger_fired = True
                            self.game.sfx.play("ui/alert_danger")
                    # If the hit killed the target, also spawn a death
                    # FX at the ship's location.
                    if not target.alive and target.cls.id not in self._death_fx_spawned:
                        self.death_fx.append(DeathFx(
                            x=target.x, y=target.y,
                            color=target.cls.hull_color,
                            seed=hash((target.cls.id, int(self.time_in_scene * 1000))) & 0xFFFF,
                        ))
                        self._death_fx_spawned.add(target.cls.id)
                    p = None  # type: ignore[assignment]
                    break
            if p is not None:
                survivors.append(p)
        self.projectiles = survivors

    def _wrap_delta(self, a: float, b: float, axis: float) -> float:
        d = a - b
        if d > axis / 2:
            d -= axis
        elif d < -axis / 2:
            d += axis
        return d

    # ------------------------------------------------------------------
    # Combat FX renderers
    # ------------------------------------------------------------------

    def _draw_impact_fx(
        self,
        screen: pygame.Surface,
        fx: "ImpactFx",
        ox: float, oy: float, scale: float,
    ) -> None:
        """Expanding blast-puff at the impact point. Two concentric
        rings — a fast bright inner flash, then a slower outer halo —
        fading to transparent over the FX duration.
        """
        progress = min(1.0, fx.t / fx.duration)
        sx, sy = self._world_to_screen(fx.x, fx.y, ox, oy, scale)
        # Inner flash: fades fastest, brightest at t=0
        inner_r = max(1, int((6 + fx.max_radius * 0.35 * progress) * scale))
        inner_a = int(255 * (1 - progress) ** 2)
        # Outer halo: expands more, fades slower
        outer_r = max(1, int(fx.max_radius * (0.4 + 0.9 * progress) * scale))
        outer_a = int(180 * (1 - progress))
        # Brighten color toward white for the flash
        flash_color = (
            min(255, int(fx.color[0] * 0.4 + 255 * 0.6)),
            min(255, int(fx.color[1] * 0.4 + 230 * 0.6)),
            min(255, int(fx.color[2] * 0.4 + 200 * 0.6)),
        )
        size = outer_r * 2 + 4
        surf = pygame.Surface((size, size), pygame.SRCALPHA)
        c = (size // 2, size // 2)
        # Outer halo
        pygame.draw.circle(surf, (*fx.color, outer_a), c, outer_r)
        # Inner bright flash
        pygame.draw.circle(surf, (*flash_color, inner_a), c, inner_r)
        screen.blit(surf, (int(sx) - size // 2, int(sy) - size // 2),
                    special_flags=pygame.BLEND_RGBA_ADD)

    def _draw_death_fx(
        self,
        screen: pygame.Surface,
        fx: "DeathFx",
        ox: float, oy: float, scale: float,
    ) -> None:
        """Ship-destruction explosion. Three layered effects:
        1. Bright central core flash (peaks early, fades fast)
        2. Expanding shockwave ring (white-yellow, grows to ~70 wu)
        3. 14 colored debris particles flying outward (in hull color)
        """
        progress = min(1.0, fx.t / fx.duration)
        sx, sy = self._world_to_screen(fx.x, fx.y, ox, oy, scale)
        # 1. Core flash — peaks at progress ~0.15
        flash_curve = max(0.0, 1.0 - abs(progress - 0.10) * 7)
        flash_r = max(2, int((10 + 20 * flash_curve) * scale))
        flash_a = int(255 * flash_curve)
        # 2. Shockwave ring — expanding outward
        ring_r = max(1, int(70 * progress * scale))
        ring_thick = max(1, int(4 * (1 - progress) * scale))
        ring_a = int(220 * (1 - progress))
        size = ring_r * 2 + ring_thick * 2 + 8
        surf = pygame.Surface((size, size), pygame.SRCALPHA)
        c = (size // 2, size // 2)
        # Shockwave ring
        if ring_r > 0 and ring_a > 0:
            pygame.draw.circle(surf, (255, 240, 200, ring_a), c, ring_r, ring_thick)
        # Core flash
        if flash_a > 0:
            pygame.draw.circle(surf, (255, 240, 200, flash_a), c, flash_r)
            pygame.draw.circle(surf, (255, 255, 230, flash_a), c,
                               max(1, flash_r // 2))
        screen.blit(surf, (int(sx) - size // 2, int(sy) - size // 2),
                    special_flags=pygame.BLEND_RGBA_ADD)
        # 3. Debris particles — 14 colored chunks radiating outward.
        # Deterministic per fx.seed so the pattern is stable per playback.
        rng = random.Random(fx.seed)
        for i in range(14):
            angle = (i / 14) * math.tau + rng.uniform(-0.18, 0.18)
            speed = rng.uniform(30, 80)
            life = rng.uniform(0.6, 1.0)
            t_frac = min(1.0, fx.t / life)
            if t_frac >= 1.0:
                continue
            dist = speed * fx.t
            px = fx.x + math.cos(angle) * dist
            py = fx.y + math.sin(angle) * dist
            psx, psy = self._world_to_screen(px, py, ox, oy, scale)
            chunk_a = int(220 * (1 - t_frac))
            chunk_r = max(1, int(rng.uniform(2, 4) * scale))
            chunk_surf = pygame.Surface((chunk_r * 2 + 2, chunk_r * 2 + 2),
                                         pygame.SRCALPHA)
            pygame.draw.circle(chunk_surf, (*fx.color, chunk_a),
                                (chunk_r + 1, chunk_r + 1), chunk_r)
            screen.blit(chunk_surf, (int(psx) - chunk_r - 1, int(psy) - chunk_r - 1))

    # ------------------------------------------------------------------
    # Result + finish
    # ------------------------------------------------------------------

    def _record_result(
        self,
        winner: ShipState | None,
        loser: ShipState | None,
        timed_out: bool = False,
    ) -> None:
        self.result = CombatResult(
            winner_side=winner.side if winner else None,
            winner_ship=winner.cls if winner else None,
            loser_ship=loser.cls if loser else None,
            duration=self.time_in_scene,
            timed_out=timed_out,
        )
        self.time_since_result = 0.0

    def _finish(self) -> None:
        assert self.game is not None
        if self.on_finish is not None:
            self.on_finish(self.result)
        else:
            # Default: bounce back to SuperMelee picker
            from scz.combat.super_melee import SuperMeleeScene
            self.game.set_scene(SuperMeleeScene())

    def _result_text(self) -> str:
        if self.result is None:
            return ""
        if self.result.winner_side is None:
            return "DOUBLE KO"
        winner_name = (
            self.result.winner_ship.name if self.result.winner_ship else "?"
        )
        if self.result.timed_out:
            return f"TIMEOUT  ·  {winner_name} stands"
        return f"VICTORY  ·  {winner_name}"

    # ------------------------------------------------------------------
    # Rendering helpers
    # ------------------------------------------------------------------

    def _scale(self) -> float:
        # Fit the arena to the window. Slight margin.
        sx = (self.screen_w - 80) / ARENA_W
        sy = (self.screen_h - 200) / ARENA_H
        return min(sx, sy)

    def _world_to_screen(
        self, x: float, y: float, ox: float, oy: float, scale: float
    ) -> tuple[float, float]:
        return (ox + x * scale, oy + y * scale)

    def _load_projectile_sprite(self, ship_id: str) -> pygame.Surface | None:
        """Return the projectile sprite for a ship's primary weapon, or None.

        Looks for `projectile_<ship_id>.png` in `SHIP_SPRITE_DIR`. The
        loaded image is scaled so its longest axis is
        `PROJECTILE_SPRITE_BASE_SIZE` world units and cached. Missing
        loads fall back to the colored-circle rendering in the draw loop.
        """
        if ship_id in self._projectile_sprite_cache:
            return self._projectile_sprite_cache[ship_id]
        path = os.path.join(SHIP_SPRITE_DIR, f"projectile_{ship_id}.png")
        if not os.path.isfile(path):
            self._projectile_sprite_cache[ship_id] = None
            return None
        try:
            img = pygame.image.load(path).convert_alpha()
            w, h = img.get_size()
            longest = max(w, h)
            if longest != PROJECTILE_SPRITE_BASE_SIZE:
                f = PROJECTILE_SPRITE_BASE_SIZE / longest
                img = pygame.transform.smoothscale(
                    img, (max(1, int(w * f)), max(1, int(h * f))),
                )
        except (pygame.error, OSError):
            img = None
        self._projectile_sprite_cache[ship_id] = img
        return img

    def _load_starfield_sprite(self) -> pygame.Surface | None:
        """Return the painted starfield backdrop or None if missing.

        Cached on the scene instance — first call attempts load, missing
        loads are remembered so we don't hit disk every frame. Sized
        scaling is handled at blit time, not here.
        """
        if self._starfield_sprite is False:
            return None
        if isinstance(self._starfield_sprite, pygame.Surface):
            return self._starfield_sprite
        # First attempt
        path = os.path.join("assets", "combat", "starfield.png")
        if not os.path.isfile(path):
            self._starfield_sprite = False
            return None
        try:
            img = pygame.image.load(path).convert_alpha()
            self._starfield_sprite = img
            return img
        except (pygame.error, OSError):
            self._starfield_sprite = False
            return None

    def _load_ship_sprite(self, ship_id: str) -> pygame.Surface | None:
        """Return the base (nose-up) sprite for a ship class, or None.

        Sprites live in `SHIP_SPRITE_DIR/SHIP_SPRITES[ship_id]`. The
        loaded image is scaled so its longest axis is `SHIP_SPRITE_BASE_SIZE`
        world units and cached. Missing/failed loads are cached as None
        so the fallback polygon path is taken without re-trying every
        frame.
        """
        if ship_id in self._ship_sprite_cache:
            return self._ship_sprite_cache[ship_id]
        fname = SHIP_SPRITES.get(ship_id)
        if fname is None:
            self._ship_sprite_cache[ship_id] = None
            return None
        path = os.path.join(SHIP_SPRITE_DIR, fname)
        if not os.path.isfile(path):
            self._ship_sprite_cache[ship_id] = None
            return None
        try:
            img = pygame.image.load(path).convert_alpha()
            w, h = img.get_size()
            longest = max(w, h)
            if longest != SHIP_SPRITE_BASE_SIZE:
                f = SHIP_SPRITE_BASE_SIZE / longest
                img = pygame.transform.smoothscale(
                    img, (max(1, int(w * f)), max(1, int(h * f))),
                )
        except (pygame.error, OSError):
            img = None
        self._ship_sprite_cache[ship_id] = img
        return img

    def _draw_ship(
        self,
        screen: pygame.Surface,
        ship: ShipState,
        ox: float,
        oy: float,
        scale: float,
    ) -> None:
        if not ship.alive:
            # Brief wreck
            sx, sy = self._world_to_screen(ship.x, ship.y, ox, oy, scale)
            pygame.draw.circle(screen, (180, 60, 60), (int(sx), int(sy)), 14, 1)
            pygame.draw.circle(screen, (140, 40, 40), (int(sx), int(sy)), 8, 1)
            return
        sx, sy = self._world_to_screen(ship.x, ship.y, ox, oy, scale)

        # Sprite path — try to blit a rotated Firefly-generated sprite.
        sprite = self._load_ship_sprite(ship.cls.id)
        if sprite is not None:
            # Convert game heading to pygame rotation. heading=0 means
            # nose pointing -y (up); pygame.transform.rotate is CCW. So
            # angle_degrees = -math.degrees(heading) gives the right
            # facing for sprites authored nose-up.
            angle_deg = -math.degrees(ship.heading)
            rotated = pygame.transform.rotozoom(sprite, angle_deg, scale)
            if ship.hit_flash > 0:
                t = ship.hit_flash / 0.25
                # Additive overlay tints the sprite warm-white on hit.
                tint = (int(t * 180), int(t * 90), int(t * 90), 0)
                flashed = rotated.copy()
                flashed.fill(tint, special_flags=pygame.BLEND_RGBA_ADD)
                rotated = flashed
            rect = rotated.get_rect(center=(int(sx), int(sy)))
            screen.blit(rotated, rect)
            if ship.cls.shield_max > 0 and ship.shield > 0:
                frac = max(0.0, min(1.0, ship.shield / ship.cls.shield_max))
                shield_color = (
                    min(255, int(120 * frac + 60)),
                    min(255, int(160 * frac + 60)),
                    min(255, int(180 * frac + 60)),
                )
                radius = max(8, int(max(rect.width, rect.height) * 0.6))
                pygame.draw.circle(
                    screen, shield_color, (int(sx), int(sy)), radius, 1,
                )
            return

        # Polygon fallback (ships without sprites yet).
        cos_h = math.cos(ship.heading)
        sin_h = math.sin(ship.heading)
        # Silhouette: simple shape; mass + style suggest tweaks
        size = 14
        s = ship.cls.silhouette
        if s in ("scout", "skiff"):
            pts = [(0, -size), (-size * 0.65, size * 0.55), (size * 0.65, size * 0.55)]
        elif s == "blade":
            pts = [(0, -size), (-size * 0.4, size * 0.6), (0, size * 0.3), (size * 0.4, size * 0.6)]
        elif s in ("heavy", "cruiser"):
            size = 18
            pts = [
                (0, -size), (-size * 0.85, -size * 0.1),
                (-size * 0.6, size * 0.7), (size * 0.6, size * 0.7),
                (size * 0.85, -size * 0.1),
            ]
        elif s == "warship":
            size = 16
            pts = [(0, -size), (-size, size * 0.4), (-size * 0.3, size * 0.5),
                   (size * 0.3, size * 0.5), (size, size * 0.4)]
        else:  # sentinel
            size = 15
            pts = [(0, -size), (-size * 0.5, -size * 0.2), (-size * 0.7, size * 0.5),
                   (size * 0.7, size * 0.5), (size * 0.5, -size * 0.2)]
        rotated = []
        for lx, ly in pts:
            rx = lx * cos_h - ly * sin_h
            ry = lx * sin_h + ly * cos_h
            rotated.append((sx + rx * scale, sy + ry * scale))
        # Flash on damage
        body_color = ship.cls.hull_color
        if ship.hit_flash > 0:
            t = ship.hit_flash / 0.25
            body_color = (
                min(255, int(body_color[0] + t * 120)),
                min(255, int(body_color[1] + t * 60)),
                min(255, int(body_color[2] + t * 60)),
            )
        pygame.draw.polygon(screen, body_color, rotated)
        pygame.draw.polygon(screen, ship.cls.accent_color, rotated, 1)
        # Shield ring
        if ship.cls.shield_max > 0 and ship.shield > 0:
            frac = max(0.0, min(1.0, ship.shield / ship.cls.shield_max))
            shield_color = (
                min(255, int(120 * frac + 60)),
                min(255, int(160 * frac + 60)),
                min(255, int(180 * frac + 60)),
            )
            pygame.draw.circle(
                screen, shield_color, (int(sx), int(sy)),
                max(1, int((size + 6) * scale * 1.3)), 1,
            )

    def _draw_hud(self, screen: pygame.Surface) -> None:
        assert self.font is not None
        # Side panels — left = Precursor, right = Homesteader
        for ship, x_anchor, align in (
            (self.precursor, 24, "left"),
            (self.homesteader, self.screen_w - 380, "left"),
        ):
            cls = ship.cls
            y = 24
            screen.blit(
                self.font.render(cls.name, True, ship.cls.accent_color),
                (x_anchor, y),
            )
            y += 28
            screen.blit(
                self.font.render(
                    f"{cls.side.upper():<12s}  {cls.points} pts",
                    True, (180, 180, 200),
                ),
                (x_anchor, y),
            )
            y += 24
            # Hull bar
            self._bar(
                screen, x_anchor, y, 320, 12,
                ship.hull / max(1, cls.hull_max),
                (220, 80, 80),
                f"HULL   {int(ship.hull):3d}/{cls.hull_max}",
            )
            y += 22
            # Shield bar (if any)
            if cls.shield_max > 0:
                self._bar(
                    screen, x_anchor, y, 320, 12,
                    ship.shield / max(1, cls.shield_max),
                    (90, 180, 240),
                    f"SHIELD {int(ship.shield):3d}/{cls.shield_max}",
                )
                y += 22
            else:
                screen.blit(
                    self.font.render("(no shields)", True, (130, 140, 170)),
                    (x_anchor, y),
                )
                y += 22
            # Energy bar
            self._bar(
                screen, x_anchor, y, 320, 8,
                ship.energy / max(1, cls.energy_max),
                (140, 220, 160),
                f"NRG    {int(ship.energy):3d}/{int(cls.energy_max)}",
            )

        # Center bottom — time remaining
        remaining = max(0, self.max_duration - self.time_in_scene)
        timer = self.font.render(
            f"FIGHT  ·  t={self.time_in_scene:5.1f}s  ·  cap {self.max_duration:.0f}s",
            True, (180, 190, 210),
        )
        tw, _ = timer.get_size()
        screen.blit(timer, ((self.screen_w - tw) // 2, self.screen_h - 36))

    def _bar(
        self,
        screen: pygame.Surface,
        x: int,
        y: int,
        w: int,
        h: int,
        frac: float,
        color: tuple[int, int, int],
        label: str,
    ) -> None:
        assert self.font is not None
        frac = max(0.0, min(1.0, frac))
        pygame.draw.rect(screen, (30, 30, 50), (x, y, w, h))
        pygame.draw.rect(screen, color, (x, y, int(w * frac), h))
        pygame.draw.rect(screen, (90, 100, 130), (x, y, w, h), 1)
        screen.blit(self.font.render(label, True, (200, 210, 230)), (x + w + 8, y - 3))
