"""Generate a single-file HTML audio player for Aaron's review pass.

Scans assets/music/ (every context dir with a manifest.json) and
assets/sfx/ (every .wav under it) and emits a self-contained HTML
page with:
  - Per music context: "play all stems" sync button + per-stem volume
    sliders + per-stem solo button. Plays as the game would mix them.
  - Per SFX category: one-click preview + a (loop) indicator where the
    spec marks it.
  - Spec metadata visible: key/bpm/description/SC2 idiom for music;
    prompt text for SFX.

The page expects to be served from the project root (relative paths
under assets/music and assets/sfx). Pair this build script with:
    python -m http.server 8770
in the project root, then navigate to
    http://localhost:8770/tools/audio_player.html

Re-run this script any time you generate new audio.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MUSIC_ROOT = ROOT / "assets" / "music"
SFX_ROOT = ROOT / "assets" / "sfx"
OUT_PATH = Path(__file__).resolve().parent / "audio_player.html"


def _load_manifest(ctx_dir: Path) -> dict:
    p = ctx_dir / "manifest.json"
    if not p.exists():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def _list_music_contexts() -> list[tuple[Path, dict]]:
    """Return (ctx_dir, manifest) for every music context found.

    Skips dirs starting with '_' (e.g. '_quality_probe' holds prompt
    A/B test artifacts — they're useful on disk but shouldn't appear
    on the review page)."""
    if not MUSIC_ROOT.is_dir():
        return []
    items: list[tuple[Path, dict]] = []
    for d in sorted(MUSIC_ROOT.iterdir()):
        if d.is_dir() and not d.name.startswith("_"):
            items.append((d, _load_manifest(d)))
    return items


def _list_sfx_groups() -> dict[str, list[Path]]:
    """Group SFX paths by their immediate parent dir."""
    if not SFX_ROOT.is_dir():
        return {}
    groups: dict[str, list[Path]] = {}
    for p in sorted(SFX_ROOT.rglob("*.wav")):
        rel_parent = p.parent.relative_to(SFX_ROOT)
        key = str(rel_parent).replace("\\", "/")
        groups.setdefault(key, []).append(p)
    return groups


def _try_lookup_sfx_spec(name: str, out_subdir: str) -> dict | None:
    """Pull the prompt + duration_s + loop flag from audio_sfx_specs."""
    try:
        sys.path.insert(0, str(ROOT / "tools"))
        from audio_sfx_specs import ALL_SFX  # type: ignore
    except Exception:
        return None
    target_subdir = out_subdir
    for s in ALL_SFX:
        if s.name == name and s.out_subdir == target_subdir:
            return {
                "prompt": s.prompt,
                "duration_s": s.duration_s,
                "loop": s.loop,
                "category": s.category,
                "species_id": s.species_id,
            }
    return None


def _audio_url(asset_path: Path) -> str:
    """Project-root-relative URL the served HTML can hit."""
    rel = asset_path.relative_to(ROOT).as_posix()
    return f"../{rel}"


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;").replace("'", "&#39;"))


def _backend_chip_html(backend: str) -> str:
    """Compact LOCAL/ELEVEN/DERIVED chip displayed alongside the name."""
    if not backend:
        return ""
    b = backend.lower()
    if "elevenlabs" in b:
        return '<span class="backend-chip backend-eleven" title="Generated by ElevenLabs">ELEVEN</span>'
    if "audioldm" in b or "local" in b:
        return '<span class="backend-chip backend-local" title="Generated by local AudioLDM2-Music server">LOCAL</span>'
    if "derived" in b or "reverse" in b:
        return '<span class="backend-chip backend-derived" title="Derived: ' + _esc(backend) + '">DERIVED</span>'
    return f'<span class="backend-chip backend-unknown" title="{_esc(backend)}">?</span>'


def _stem_backend_from_manifest(manifest: dict, stem_name: str) -> str:
    """Per-stem backend lookup. Manifests written by the new generator
    record per-stem backend; older R1 manifests record only a context-
    level backend field. Fall back to the context-level field if no
    per-stem info is available."""
    stems = (manifest or {}).get("stems", {})
    entry = stems.get(stem_name)
    if isinstance(entry, dict) and entry.get("backend"):
        return entry["backend"]
    return (manifest or {}).get("backend", "")


def _load_sfx_provenance() -> dict:
    p = ROOT / "assets" / "sfx" / "_provenance.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _review_actions_html(review_key: str, review_status: str, review_notes: str) -> str:
    """Approve / Re-roll / Reject buttons + notes editor.

    Mirror of the image-reviewer pattern. POSTs to /api/audio-review/<key>
    on click; the audio_review_server.py (which is the image_review_server
    extended on 2026-05-17) persists to assets/_audio_review.json.
    """
    return f"""
        <div class="review-actions" data-review-key="{_esc(review_key)}" data-review-status="{_esc(review_status)}">
          <button class="action-btn approve" data-action="keep" title="Approve — lock this take">✓ Approve</button>
          <button class="action-btn reroll" data-action="reroll_requested" title="Mark for re-generation with adjusted prompt">↻ Re-roll</button>
          <button class="action-btn reject" data-action="reject" title="Reject — don't use">✗ Reject</button>
          <span class="chip chip-{_esc(review_status)} review-chip">{_esc(review_status)}</span>
        </div>
        <details class="notes-edit">
          <summary>📝 Note</summary>
          <textarea class="notes-input" rows="2" placeholder="what to change on re-roll, why rejected, mix preferences, etc.">{_esc(review_notes)}</textarea>
          <button class="save-notes-btn">Save note</button>
          <span class="save-feedback"></span>
        </details>"""


def _render_music_section(ctx_dir: Path, manifest: dict, review_state: dict) -> str:
    name = ctx_dir.name
    key = manifest.get("key", "?")
    bpm = manifest.get("bpm", "?")
    desc = manifest.get("description", "")
    category = manifest.get("category", "")
    dur = manifest.get("duration_s", "?")
    review_key = f"music/{name}"
    review_entry = review_state.get(review_key, {}) or {}
    review_status = review_entry.get("status") or "pending"
    review_notes = review_entry.get("notes") or ""

    # Hide already-committed audio from the review page. Aaron 2026-05-19:
    # 'remove the approved from the list, the page was locking up'.
    # 'keep' = Aaron approved + committed; 'wired' = same, also in active
    # game use. Neither needs further review and rendering all 100+
    # players bogs down the browser.
    if review_status in ("keep", "wired"):
        return ""

    audio_files = (
        sorted(ctx_dir.glob("*.mp3"))
        + sorted(ctx_dir.glob("*.ogg"))
        + sorted(ctx_dir.glob("*.wav"))
    )
    # Order stems: bass, percussion, pad, lead, ambient, drone, pulse, texture,
    # then any state-driven or extra stems alphabetical.
    pref_order = ["bass", "percussion", "pad", "lead", "ambient",
                  "drone", "pulse", "texture"]
    def stem_sort(p: Path):
        try:
            return (0, pref_order.index(p.stem), p.stem)
        except ValueError:
            return (1, 0, p.stem)
    audio_files.sort(key=stem_sort)

    if not audio_files:
        return ""

    # Backend chip for the WHOLE context (from manifest top-level field).
    ctx_backend = manifest.get("backend", "")
    ctx_backend_html = _backend_chip_html(ctx_backend)

    stems_html = []
    for p in audio_files:
        url = _audio_url(p)
        stem_name = p.stem
        is_state = stem_name not in pref_order
        cls = "stem state-stem" if is_state else "stem"
        # Per-stem backend (falls back to context backend)
        stem_backend = _stem_backend_from_manifest(manifest, stem_name)
        stems_html.append(f"""
        <div class="{cls}">
          <label>{_esc(stem_name)}{' (state)' if is_state else ''} {_backend_chip_html(stem_backend)}</label>
          <input type="range" min="0" max="1" step="0.01" value="0.85"
                 oninput="setStemVol('{_esc(name)}', '{_esc(stem_name)}', this.value); this.nextElementSibling.textContent = (+this.value).toFixed(2);" />
          <span class="vol-readout">0.85</span>
          <button class="solo-btn" onclick="soloStem('{_esc(name)}', '{_esc(stem_name)}')">solo</button>
          <button class="mute-btn" onclick="toggleMute('{_esc(name)}', '{_esc(stem_name)}', this)">mute</button>
          <audio data-ctx="{_esc(name)}" data-stem="{_esc(stem_name)}"
                 src="{url}" preload="auto" loop></audio>
        </div>""")

    return f"""
    <section class="music-ctx" data-ctx="{_esc(name)}" data-review-status="{_esc(review_status)}">
      <h3>{_esc(name)} {ctx_backend_html} <span class="meta">— {_esc(str(key))} / {_esc(str(bpm))} bpm / {_esc(str(dur))}s loop</span></h3>
      <p class="desc">{_esc(desc)}</p>
      <p class="category">[{_esc(category)}]</p>
      <div class="ctx-ctrl">
        <button class="play-btn" onclick="playAllStems('{_esc(name)}')">▶ Play all stems</button>
        <button class="stop-btn" onclick="stopAllStems('{_esc(name)}')">⏹ Stop</button>
        <button class="reset-btn" onclick="resetStems('{_esc(name)}')">reset volumes</button>
      </div>
      {_review_actions_html(review_key, review_status, review_notes)}
      <div class="stems">{''.join(stems_html)}
      </div>
    </section>"""


def _render_sfx_item(group_label: str, p: Path,
                     review_state: dict, sfx_provenance: dict,
                     show_subdir: bool = True) -> str:
    """Render one SFX item (one card). Decoupled from group rendering so
    the species-bucket layout can interleave items from multiple subdirs
    under a single species heading (e.g. all Furling-faction ship SFX
    under one Furling section)."""
    spec = _try_lookup_sfx_spec(p.stem, group_label) or {}
    prompt = spec.get("prompt", "")
    dur = spec.get("duration_s", "")
    loop_flag = spec.get("loop", False)
    cat = spec.get("category", "")
    # Per-SFX review state. Key is the audio-review key: sfx/<subdir>/<name>
    sfx_key = f"sfx/{group_label}/{p.stem}"
    review_entry = review_state.get(sfx_key, {}) or {}
    review_status = review_entry.get("status") or "pending"
    review_notes = review_entry.get("notes") or ""

    # Hide already-committed SFX from the review page (see same comment
    # in _render_music_section).
    if review_status in ("keep", "wired"):
        return ""
    # Per-SFX backend provenance. Key shape: <subdir>/<name>
    prov_key = f"{group_label}/{p.stem}"
    prov_entry = sfx_provenance.get(prov_key) or {}
    backend = prov_entry.get("backend") if isinstance(prov_entry, dict) else (prov_entry or "")
    backend_chip = _backend_chip_html(backend or "")
    # Subdir badge — only shown in species buckets (Furling has multiple
    # ships, so callers want it; UI/Lander/Scan buckets have a single
    # subdir, so callers suppress to reduce noise).
    subdir_badge = (f'<span class="sfx-subdir">{_esc(group_label)}/</span>'
                    if show_subdir else "")
    return f"""
    <div class="sfx-item{' loopable' if loop_flag else ''}" data-review-status="{_esc(review_status)}">
      <button class="play-sfx" onclick="playSfx(this)">▶</button>
      <span class="sfx-name">{subdir_badge}{_esc(p.stem)} {backend_chip}</span>
      <span class="sfx-meta">{_esc(str(dur))}s{' · LOOP' if loop_flag else ''}{(' · ' + _esc(cat)) if cat else ''}</span>
      <span class="sfx-prompt">{_esc(prompt)}</span>
      <audio src="{_audio_url(p)}" preload="metadata" {'loop' if loop_flag else ''}></audio>
      {_review_actions_html(sfx_key, review_status, review_notes)}
    </div>"""


def _render_sfx_group(group_label: str, paths: list[Path],
                      review_state: dict, sfx_provenance: dict) -> str:
    items_html = [
        _render_sfx_item(group_label, p, review_state, sfx_provenance,
                         show_subdir=False)
        for p in paths
    ]
    return f"""
    <section class="sfx-group">
      <h3>{_esc(group_label)} <span class="meta">— {len(paths)} sound{'s' if len(paths)!=1 else ''}</span></h3>
      <div class="sfx-list">{''.join(items_html)}
      </div>
    </section>"""


# ---------------------------------------------------------------------------
# Species + universal bucket assignment for Aaron's review pass.
# Aaron 2026-05-19: "organize it all by species, or if not related to a
# species, sub-categorize as UI, universal, etc..."
# ---------------------------------------------------------------------------

# Bucket display order: Furling (player) first, then other species
# alphabetical, then universal categories.
BUCKET_ORDER = [
    "Furling",
    "Androsynth", "Arilou", "Burvixese", "Chenjesu", "Lemmkin",
    "Melnorme", "Mmrnmhrm", "Mycon", "Proto-Qor-Ah", "Proto-Ur-Quan",
    "Slylandro", "Taalo", "Thinn (Planar)", "Utwig",
    "Travel & Navigation", "Combat", "Story Moments", "Endings",
    "UI", "Lander Tools", "Scan",
    "Universal — Title", "Universal — Misc",
]


def _bucket_for_music(name: str) -> str:
    """Map a music-context name to its review bucket."""
    if name in ("arilou", "arilou_sages_grove"):
        return "Arilou"
    if name in ("androsynth", "androsynth_crash_site"):
        return "Androsynth"
    if name == "burvixese":
        return "Burvixese"
    if name == "chenjesu":
        return "Chenjesu"
    if name == "lemmkin":
        return "Lemmkin"
    if name in ("melnorme", "melnorme_bio_cargo_hold", "bargainers"):
        return "Melnorme"
    if name == "mmrnmhrm":
        return "Mmrnmhrm"
    if name in ("mycon", "mycon_hive_awakening"):
        return "Mycon"
    if name in ("planar", "thinn"):
        return "Thinn (Planar)"
    if name == "slylandro" or name.startswith("slylandro"):
        return "Slylandro"
    if name == "taalo":
        return "Taalo"
    if name == "utwig":
        return "Utwig"
    # Furling player content (homeworld + civil-war faction councils +
    # faction-named themes like 'cleanser_council').
    if (name == "furling_home"
            or name.startswith("council_")
            or "_council" in name):
        return "Furling"
    # Universal context-music categories.
    if name.startswith("combat_"):
        return "Combat"
    if name.startswith("ending_"):
        return "Endings"
    if (name.startswith("hyperspace")
            or name.startswith("system_travel")
            or name.startswith("planet_lander")
            or name.startswith("planet_orbit")
            or name.startswith("quasispace")):
        return "Travel & Navigation"
    if name in ("others_reveal", "tension_other_ripple",
                "rainbow_seeding_climax", "proto_species_wonder"):
        return "Story Moments"
    if name == "title_menu":
        return "Universal — Title"
    return "Universal — Misc"


def _bucket_for_sfx(out_subdir: str) -> str:
    """Map a SFX subdir to its review bucket. The subdir is the relative
    path under assets/sfx (e.g. 'ships/arilou_skiff', 'ui', 'lander/...')."""
    # Ship-specific SFX (weapon fire/impact) — bucket by owning species.
    if out_subdir.startswith("ships/"):
        ship_id = out_subdir[len("ships/"):].split("/", 1)[0]
        if ship_id in ("furling_scout", "persuader_vessel", "defender_vessel",
                       "cleanser_cruiser", "sentry_drone_47t"):
            return "Furling"
        if ship_id == "arilou_skiff":
            return "Arilou"
        if ship_id == "androsynth_cruiser":
            return "Androsynth"
        if ship_id == "melnorme_trader":
            return "Melnorme"
        if ship_id == "mmrnmhrm_sentinel":
            return "Mmrnmhrm"
        if ship_id == "lemmkin_skitter":
            return "Lemmkin"
        if ship_id == "proto_ur_quan":
            return "Proto-Ur-Quan"
        if ship_id == "proto_qor_ah":
            return "Proto-Qor-Ah"
        return "Universal — Misc"
    # Universal sub-categories.
    head = out_subdir.split("/", 1)[0]
    if head == "ui":
        return "UI"
    if head == "lander":
        return "Lander Tools"
    if head == "scan":
        return "Scan"
    return "Universal — Misc"


def _render_bucket_section(
    bucket: str,
    music_items: list[tuple[Path, dict]],
    sfx_items: list[tuple[str, Path]],
    review_state: dict,
    sfx_provenance: dict,
) -> str:
    """Render one bucket: a species or universal category. Contains the
    bucket's music contexts (full multi-stem players) AND its SFX items
    (compact one-line cards). Items whose review status is `keep` or
    `wired` are filtered out by the per-item renderers, so a bucket
    that's fully approved disappears from the page entirely."""
    if not music_items and not sfx_items:
        return ""
    # Render items up-front and count what actually survives the
    # status filter, so we don't emit an empty bucket section.
    music_html_pieces: list[str] = []
    for ctx_dir, manifest in music_items:
        s = _render_music_section(ctx_dir, manifest, review_state)
        if s.strip():
            music_html_pieces.append(s)

    show_subdir = bucket not in ("UI", "Lander Tools", "Scan")
    sfx_html_pieces: list[str] = []
    for subdir, p in sfx_items:
        s = _render_sfx_item(subdir, p, review_state, sfx_provenance,
                             show_subdir=show_subdir)
        if s.strip():
            sfx_html_pieces.append(s)

    if not music_html_pieces and not sfx_html_pieces:
        # Every item in this bucket is already committed; skip entirely.
        return ""

    anchor = ("bucket-" + bucket.lower()
              .replace(" ", "-").replace("(", "").replace(")", "")
              .replace("—", "").replace("--", "-").replace("/", "-")
              .strip("-"))
    counts: list[str] = []
    if music_html_pieces:
        counts.append(f"{len(music_html_pieces)} music")
    if sfx_html_pieces:
        counts.append(f"{len(sfx_html_pieces)} SFX")
    counts_html = (f'<span class="bucket-counts">{" · ".join(counts)}</span>'
                   if counts else "")
    sections: list[str] = []
    if music_html_pieces:
        sections.append(
            '<h3 class="bucket-subheading">Music</h3>'
            + "".join(music_html_pieces)
        )
    if sfx_html_pieces:
        sections.append(
            '<h3 class="bucket-subheading">SFX</h3>'
            f'<div class="sfx-list">{"".join(sfx_html_pieces)}</div>'
        )
    return f"""
    <section class="bucket" id="{_esc(anchor)}" data-bucket="{_esc(bucket)}">
      <h2 class="bucket-heading">{_esc(bucket)} {counts_html}</h2>
      {''.join(sections)}
    </section>"""


HTML_HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SCZ Audio Review</title>
<style>
  :root {
    --bg: #0a0a0d;
    --panel: #14141a;
    --border: #2a2a36;
    --accent: #00ff88;
    --accent-dim: #006644;
    --text: #f0f0f0;
    --muted: #8888a0;
    --warn: #ffaa00;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 1.5em 2em; background: var(--bg); color: var(--text);
    font-family: -apple-system, "Segoe UI", system-ui, sans-serif;
    font-size: 14px; line-height: 1.4;
  }
  header {
    border-bottom: 2px solid var(--border); padding-bottom: 1em; margin-bottom: 1em;
    display: flex; gap: 1.5em; align-items: baseline; flex-wrap: wrap;
  }
  h1 { color: var(--accent); margin: 0; font-size: 1.6em; }
  h2 { color: var(--accent); border-bottom: 1px solid var(--border); padding-bottom: .3em; margin-top: 2em; }
  h3 { color: var(--text); margin-bottom: .2em; }
  .meta { color: var(--muted); font-weight: normal; font-size: .85em; }
  .desc { color: var(--text); margin: .2em 0; }
  .category { color: var(--warn); margin: 0 0 .8em; font-size: .85em; }
  .global-ctrl { display: flex; gap: 1em; align-items: center; }
  .global-ctrl label { color: var(--muted); }
  .music-ctx, .sfx-group {
    background: var(--panel); border: 1px solid var(--border);
    border-radius: 6px; padding: 1em 1.2em; margin-bottom: 1em;
  }
  .ctx-ctrl { display: flex; gap: .5em; margin: .5em 0; }
  button {
    background: var(--accent-dim); color: var(--accent); border: 1px solid var(--accent-dim);
    padding: .35em .8em; cursor: pointer; border-radius: 3px; font-family: inherit;
    font-size: .85em;
  }
  button:hover { background: var(--accent); color: var(--bg); }
  button.stop-btn, button.reset-btn { color: var(--muted); border-color: var(--border); background: var(--panel); }
  button.stop-btn:hover, button.reset-btn:hover { color: var(--text); }
  .stems { margin-top: .3em; }
  .stem {
    display: grid;
    grid-template-columns: 110px 240px 50px 50px 50px;
    gap: .5em; align-items: center; padding: .15em 0;
  }
  .stem label { color: var(--text); font-family: monospace; }
  .state-stem label { color: var(--warn); font-weight: bold; }
  .vol-readout { font-family: monospace; color: var(--muted); font-size: .85em; }
  input[type="range"] { accent-color: var(--accent); width: 100%; }
  .sfx-list { display: flex; flex-direction: column; gap: .25em; margin-top: .5em; }
  .sfx-item {
    display: grid;
    grid-template-columns: 50px 240px 130px 1fr;
    gap: .5em; align-items: center; padding: .25em .5em;
    border-left: 2px solid var(--border);
  }
  .sfx-item.loopable { border-left-color: var(--warn); }
  .sfx-name { font-family: monospace; color: var(--text); }
  .sfx-meta { color: var(--muted); font-size: .85em; font-family: monospace; }
  .sfx-prompt { color: var(--muted); font-size: .85em; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .play-sfx { width: 40px; }
  audio { display: none; }
  .playing { background: var(--accent); color: var(--bg) !important; }
  .summary { color: var(--muted); margin-bottom: 1em; }
  details { margin-top: .5em; }
  details summary { cursor: pointer; color: var(--accent); font-size: .85em; }

  /* Backend-provenance chips: which AI made this audio */
  .backend-chip {
    display: inline-block; font-size: .65em; font-weight: bold;
    padding: 1px 5px; margin-left: .35em; border-radius: 2px;
    letter-spacing: .04em; vertical-align: middle;
    text-transform: uppercase;
  }
  .backend-local   { background: rgba(255,170,0,.18);  color: var(--warn);   border: 1px solid var(--warn);  }
  .backend-eleven  { background: rgba(0,204,255,.18);  color: #00ccff;       border: 1px solid #00ccff; }
  .backend-derived { background: rgba(136,136,160,.20); color: var(--muted);  border: 1px solid var(--muted); }
  .backend-unknown { background: rgba(255,68,68,.15);   color: #ff4444;        border: 1px solid #ff4444; }

  /* Status-chip palette (mirrors image_review.html) */
  .chip {
    padding: .15em .55em; border-radius: 3px; font-size: .75em; font-weight: bold;
    text-transform: uppercase; letter-spacing: .05em;
  }
  .chip-pending           { background: rgba(136,136,160,.15); color: var(--muted); border: 1px solid var(--muted); }
  .chip-provisional       { background: rgba(136,204,136,.08); color: #88cc88;       border: 1px dashed #88cc88; }
  .chip-keep              { background: rgba(0,255,136,.12);   color: var(--accent); border: 1px solid var(--accent); }
  .chip-reject            { background: rgba(255,68,68,.12);   color: #ff4444;       border: 1px solid #ff4444; }
  .chip-reroll_requested  { background: rgba(255,170,0,.15);   color: var(--warn);   border: 1px solid var(--warn); }
  .chip-wired             { background: rgba(0,204,255,.12);   color: #00ccff;       border: 1px solid #00ccff; }

  /* Approve / Re-roll / Reject buttons + notes editor */
  .review-actions { display: flex; gap: .3em; margin-top: .4em; align-items: center; }
  .action-btn {
    background: var(--panel); color: var(--muted); border: 1px solid var(--border);
    padding: .3em .55em; cursor: pointer; border-radius: 3px; font-family: inherit;
    font-size: .8em; transition: background .15s, color .15s, border-color .15s;
  }
  .action-btn:hover { color: var(--text); background: #1c1c24; }
  .action-btn.approve:hover { color: var(--accent); border-color: var(--accent); }
  .action-btn.reroll:hover  { color: var(--warn);   border-color: var(--warn);   }
  .action-btn.reject:hover  { color: #ff4444;       border-color: #ff4444; }
  .action-btn.active.approve { color: var(--accent); border-color: var(--accent); background: rgba(0,255,136,.08); }
  .action-btn.active.reroll  { color: var(--warn);   border-color: var(--warn);   background: rgba(255,170,0,.08); }
  .action-btn.active.reject  { color: #ff4444;       border-color: #ff4444;       background: rgba(255,68,68,.08); }
  .action-btn:disabled { opacity: .5; cursor: not-allowed; }
  .review-chip { margin-left: .4em; }
  .notes-edit { margin-top: .25em; font-size: .8em; }
  .notes-edit summary { color: var(--muted); }
  .notes-edit summary:hover { color: var(--text); }
  .notes-input {
    width: 100%; max-width: 480px; margin-top: .3em; background: var(--bg); color: var(--text);
    border: 1px solid var(--border); border-radius: 3px; padding: .3em .5em;
    font-family: inherit; font-size: .85em; resize: vertical;
  }
  .save-notes-btn {
    background: var(--panel); color: var(--muted); border: 1px solid var(--border);
    padding: .25em .7em; margin-top: .3em; cursor: pointer; border-radius: 3px;
    font-family: inherit; font-size: .8em;
  }
  .save-notes-btn:hover { color: var(--accent); border-color: var(--accent); }
  .save-feedback { font-size: .75em; margin-left: .6em; color: var(--accent); }
  .save-feedback.error { color: #ff4444; }

  /* For SFX items the action row sits underneath the grid */
  .sfx-item .review-actions { grid-column: 1 / -1; margin-top: .15em; padding-left: 50px; }
  .sfx-item .notes-edit     { grid-column: 1 / -1; padding-left: 50px; }

  /* Bucket layout (2026-05-19 — Aaron's species-grouped review pass).
     Each species or universal category gets its own section with
     music contexts + SFX items inline. */
  .bucket {
    margin: 2em 0; padding: 1em 1.2em 1.4em;
    border: 1px solid var(--border); border-radius: 8px;
    background: linear-gradient(180deg, rgba(0,255,136,.025) 0%, transparent 80px);
  }
  .bucket-heading {
    color: var(--accent); margin: 0 0 .8em;
    border-bottom: 1px solid var(--accent-dim); padding-bottom: .35em;
    display: flex; align-items: baseline; gap: .6em;
  }
  .bucket-counts {
    color: var(--muted); font-size: .7em; font-weight: normal;
    letter-spacing: .04em;
  }
  .bucket-subheading {
    color: var(--warn); font-size: 1em; margin: 1em 0 .4em;
    font-weight: normal; letter-spacing: .04em; text-transform: uppercase;
  }
  /* Inside a bucket, nested music-ctx / sfx-list panels shed their own
     borders so the bucket frames the visual hierarchy. */
  .bucket .music-ctx { border: 1px solid var(--border); margin-bottom: .8em; }
  .bucket .sfx-list  { margin-top: 0; }

  /* SFX subdir prefix badge — disambiguates "primary_fire" across the
     Furling bucket's 5 ships, hidden in single-subdir buckets (UI/etc). */
  .sfx-subdir {
    color: var(--muted); font-size: .85em;
    font-family: monospace; opacity: .65;
  }

  /* Top-of-page bucket navigation: chips with anchor links + counts. */
  .bucket-nav {
    display: flex; flex-wrap: wrap; gap: .35em; margin: 1em 0 1.5em;
    padding: .6em .8em; background: var(--panel);
    border: 1px solid var(--border); border-radius: 6px;
    position: sticky; top: 0; z-index: 10;
  }
  .nav-chip {
    display: inline-flex; align-items: center; gap: .35em;
    padding: .25em .6em; background: rgba(0,255,136,.06);
    color: var(--accent); border: 1px solid var(--accent-dim);
    border-radius: 3px; font-size: .8em; text-decoration: none;
    transition: background .15s, border-color .15s;
  }
  .nav-chip:hover { background: rgba(0,255,136,.18); border-color: var(--accent); }
  .nav-count {
    color: var(--muted); font-size: .85em; font-weight: bold;
    background: rgba(0,0,0,.4); padding: .05em .35em; border-radius: 2px;
  }
</style>
</head>
<body>
<header>
  <h1>★ SCZ Audio Review</h1>
  <div class="global-ctrl">
    <label>Master volume</label>
    <input type="range" id="master-vol" min="0" max="1" step="0.05" value="0.7"
           oninput="setMasterVolume(this.value)" style="width: 160px;" />
    <span id="master-readout">0.70</span>
  </div>
  <button onclick="stopEverything()" class="stop-btn">⏹ STOP EVERYTHING</button>
</header>
"""


HTML_TAIL = """
<script>
// All <audio> on the page. Used for global stop + master volume scaling.
const allAudio = () => Array.from(document.querySelectorAll('audio'));
let masterVol = 0.7;

function setMasterVolume(v) {
  masterVol = +v;
  document.getElementById('master-readout').textContent = masterVol.toFixed(2);
  // Re-apply per-stem volumes since their saved level multiplies by master.
  document.querySelectorAll('.music-ctx').forEach(ctx => {
    ctx.querySelectorAll('audio').forEach(a => {
      const sv = +a.dataset.stemVol || 0.85;
      a.volume = Math.max(0, Math.min(1, sv * masterVol));
    });
  });
  document.querySelectorAll('.sfx-item').forEach(item => {
    const a = item.querySelector('audio');
    if (a) a.volume = masterVol;
  });
}

function _ctxAudios(ctxName) {
  return Array.from(document.querySelectorAll(`audio[data-ctx="${ctxName}"]`));
}

function setStemVol(ctxName, stemName, v) {
  const audios = _ctxAudios(ctxName).filter(a => a.dataset.stem === stemName);
  audios.forEach(a => {
    a.dataset.stemVol = v;
    a.volume = Math.max(0, Math.min(1, (+v) * masterVol));
  });
}

function playAllStems(ctxName) {
  stopEverythingExcept(ctxName);
  const audios = _ctxAudios(ctxName);
  audios.forEach(a => {
    a.currentTime = 0;
    if (!a.dataset.stemVol) a.dataset.stemVol = 0.85;
    a.volume = (+a.dataset.stemVol) * masterVol;
    a.play().catch(e => console.warn('play failed:', a.src, e));
  });
}

function stopAllStems(ctxName) {
  _ctxAudios(ctxName).forEach(a => { a.pause(); a.currentTime = 0; });
}

function soloStem(ctxName, stemName) {
  // Pause the others in this context, play just the target.
  stopEverythingExcept(ctxName);
  const audios = _ctxAudios(ctxName);
  audios.forEach(a => {
    if (a.dataset.stem === stemName) {
      a.currentTime = 0;
      a.volume = (+a.dataset.stemVol || 0.85) * masterVol;
      a.play().catch(e => console.warn(e));
    } else {
      a.pause();
    }
  });
}

function toggleMute(ctxName, stemName, btn) {
  const audios = _ctxAudios(ctxName).filter(a => a.dataset.stem === stemName);
  audios.forEach(a => {
    a.muted = !a.muted;
    btn.textContent = a.muted ? 'unmute' : 'mute';
    btn.classList.toggle('playing', a.muted);
  });
}

function resetStems(ctxName) {
  document.querySelectorAll(`.music-ctx[data-ctx="${ctxName}"] .stem`).forEach(stem => {
    const range = stem.querySelector('input[type="range"]');
    const readout = stem.querySelector('.vol-readout');
    const audio = stem.querySelector('audio');
    range.value = 0.85;
    readout.textContent = '0.85';
    audio.muted = false;
    audio.dataset.stemVol = 0.85;
    audio.volume = 0.85 * masterVol;
    const muteBtn = stem.querySelector('.mute-btn');
    muteBtn.textContent = 'mute';
    muteBtn.classList.remove('playing');
  });
}

function playSfx(btn) {
  const audio = btn.parentElement.querySelector('audio');
  // For non-looping SFX, stop any other SFX currently playing.
  document.querySelectorAll('.sfx-item audio').forEach(a => {
    if (a !== audio && !a.loop) { a.pause(); a.currentTime = 0; }
  });
  audio.currentTime = 0;
  audio.volume = masterVol;
  if (audio.loop && !audio.paused) {
    audio.pause();
    audio.currentTime = 0;
    btn.classList.remove('playing');
    btn.textContent = '▶';
  } else {
    audio.play().catch(e => console.warn(e));
    if (audio.loop) {
      btn.classList.add('playing');
      btn.textContent = '⏸';
    }
  }
}

function stopEverything() {
  allAudio().forEach(a => { a.pause(); a.currentTime = 0; });
  document.querySelectorAll('.play-sfx.playing').forEach(b => {
    b.classList.remove('playing'); b.textContent = '▶';
  });
}

function stopEverythingExcept(ctxName) {
  document.querySelectorAll('.music-ctx').forEach(ctx => {
    if (ctx.dataset.ctx !== ctxName) {
      ctx.querySelectorAll('audio').forEach(a => { a.pause(); a.currentTime = 0; });
    }
  });
}

// ---- localStorage persistence (so slider tweaks survive nav-aways) ----
const STATE_KEY = 'scz_audio_review_state_v1';

function loadState() {
  try {
    return JSON.parse(localStorage.getItem(STATE_KEY) || '{}');
  } catch (e) {
    return {};
  }
}
function saveState(state) {
  try { localStorage.setItem(STATE_KEY, JSON.stringify(state)); }
  catch (e) { /* quota / private-mode -- silent */ }
}
const state = loadState();
// state = { masterVol: 0.7, stems: { "ctxName__stemName": { vol: 0.85, muted: false } } }
state.stems = state.stems || {};

function _stemKey(ctxName, stemName) { return ctxName + '__' + stemName; }

// Wrap setStemVol to persist
const _origSetStemVol = setStemVol;
setStemVol = function(ctxName, stemName, v) {
  _origSetStemVol(ctxName, stemName, v);
  const k = _stemKey(ctxName, stemName);
  state.stems[k] = state.stems[k] || {};
  state.stems[k].vol = +v;
  saveState(state);
};
const _origToggleMute = toggleMute;
toggleMute = function(ctxName, stemName, btn) {
  _origToggleMute(ctxName, stemName, btn);
  const audios = _ctxAudios(ctxName).filter(a => a.dataset.stem === stemName);
  if (audios.length) {
    const k = _stemKey(ctxName, stemName);
    state.stems[k] = state.stems[k] || {};
    state.stems[k].muted = audios[0].muted;
    saveState(state);
  }
};
const _origResetStems = resetStems;
resetStems = function(ctxName) {
  _origResetStems(ctxName);
  Object.keys(state.stems).forEach(k => {
    if (k.startsWith(ctxName + '__')) delete state.stems[k];
  });
  saveState(state);
};
const _origSetMasterVolume = setMasterVolume;
setMasterVolume = function(v) {
  _origSetMasterVolume(v);
  state.masterVol = +v;
  saveState(state);
};

// On load: restore master + per-stem state. Master first so per-stem
// scaling uses the right master.
if (typeof state.masterVol === 'number') {
  const masterInput = document.getElementById('master-vol');
  masterInput.value = state.masterVol;
  setMasterVolume(state.masterVol);
}
// ============================================================
// Approve/Re-roll/Reject buttons — POST to /api/audio-review/<key>
// ============================================================
async function postAudioReview(key, payload) {
  const r = await fetch('/api/audio-review/' + encodeURIComponent(key), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  });
  if (!r.ok) throw new Error('HTTP ' + r.status + ': ' + await r.text());
  return await r.json();
}

function updateReviewChip(actionsEl, newStatus) {
  const chip = actionsEl.querySelector('.review-chip');
  if (chip) {
    chip.className = chip.className.replace(/\bchip-\S+/g, '').trim();
    chip.classList.add('chip', 'chip-' + newStatus, 'review-chip');
    chip.textContent = newStatus;
  }
  actionsEl.dataset.reviewStatus = newStatus;
  // Reflect status on the parent card too (for filter logic later).
  const card = actionsEl.closest('.music-ctx, .sfx-item');
  if (card) card.dataset.reviewStatus = newStatus;
}

function highlightActiveActionBtn(actionsEl, status) {
  actionsEl.querySelectorAll('.action-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.action === status);
  });
}

document.querySelectorAll('.review-actions').forEach(actionsEl => {
  const key = actionsEl.dataset.reviewKey;
  highlightActiveActionBtn(actionsEl, actionsEl.dataset.reviewStatus);
  actionsEl.querySelectorAll('.action-btn').forEach(btn => {
    btn.addEventListener('click', async () => {
      const newStatus = btn.dataset.action;
      actionsEl.querySelectorAll('.action-btn').forEach(b => b.disabled = true);
      try {
        await postAudioReview(key, { status: newStatus });
        updateReviewChip(actionsEl, newStatus);
        highlightActiveActionBtn(actionsEl, newStatus);
      } catch (e) {
        alert('Failed to update review: ' + e.message);
      } finally {
        actionsEl.querySelectorAll('.action-btn').forEach(b => b.disabled = false);
      }
    });
  });
});

document.querySelectorAll('.notes-edit').forEach(editEl => {
  // The actions row is the previous sibling of the notes-edit details
  const actionsEl = editEl.previousElementSibling;
  if (!actionsEl || !actionsEl.classList.contains('review-actions')) return;
  const key = actionsEl.dataset.reviewKey;
  const textarea = editEl.querySelector('.notes-input');
  const saveBtn = editEl.querySelector('.save-notes-btn');
  const feedback = editEl.querySelector('.save-feedback');
  if (!saveBtn) return;
  saveBtn.addEventListener('click', async () => {
    saveBtn.disabled = true;
    feedback.classList.remove('error');
    feedback.textContent = 'saving...';
    try {
      await postAudioReview(key, { notes: textarea.value });
      feedback.textContent = '✓ saved';
      setTimeout(() => { feedback.textContent = ''; }, 2000);
    } catch (e) {
      feedback.classList.add('error');
      feedback.textContent = '✗ ' + e.message;
    } finally {
      saveBtn.disabled = false;
    }
  });
});

// Initialize every audio's stemVol dataset (must happen before applying
// restored values so the master-volume rescale works).
document.querySelectorAll('audio[data-stem]').forEach(a => {
  a.dataset.stemVol = 0.85;
  a.volume = 0.85 * masterVol;
});
// Now apply restored per-stem values, walking the actual stem rows so the
// slider position + readout + mute button text all stay in sync.
document.querySelectorAll('.music-ctx').forEach(ctx => {
  const ctxName = ctx.dataset.ctx;
  ctx.querySelectorAll('.stem').forEach(stem => {
    const audio = stem.querySelector('audio');
    const range = stem.querySelector('input[type="range"]');
    const readout = stem.querySelector('.vol-readout');
    const muteBtn = stem.querySelector('.mute-btn');
    const k = _stemKey(ctxName, audio.dataset.stem);
    const s = state.stems[k];
    if (!s) return;
    if (typeof s.vol === 'number') {
      range.value = s.vol;
      readout.textContent = (+s.vol).toFixed(2);
      audio.dataset.stemVol = s.vol;
      audio.volume = (+s.vol) * masterVol;
    }
    if (s.muted) {
      audio.muted = true;
      muteBtn.textContent = 'unmute';
      muteBtn.classList.add('playing');
    }
  });
});
</script>
</body>
</html>
"""


def _load_audio_review_manifest() -> dict:
    """Read assets/_audio_review.json so the initial render can show each
    item's current review status (chip + active-button highlight)."""
    p = ROOT / "assets" / "_audio_review.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def build() -> Path:
    contexts = _list_music_contexts()
    sfx_groups = _list_sfx_groups()
    review_state = _load_audio_review_manifest()
    sfx_provenance = _load_sfx_provenance()

    # Bucket music contexts + SFX items by species / universal category.
    # music_buckets[bucket] -> list[(ctx_dir, manifest)]
    # sfx_buckets[bucket] -> list[(subdir, path)]
    music_buckets: dict[str, list[tuple[Path, dict]]] = {}
    for ctx_dir, manifest in contexts:
        bucket = _bucket_for_music(ctx_dir.name)
        music_buckets.setdefault(bucket, []).append((ctx_dir, manifest))

    sfx_buckets: dict[str, list[tuple[str, Path]]] = {}
    for subdir, paths in sfx_groups.items():
        for p in paths:
            bucket = _bucket_for_sfx(subdir)
            sfx_buckets.setdefault(bucket, []).append((subdir, p))
    # Sort SFX inside each bucket: subdir first, then by filename so
    # primary_fire/primary_impact/special_fire/special_impact cluster
    # per ship.
    for items in sfx_buckets.values():
        items.sort(key=lambda t: (t[0], t[1].name))

    # Order buckets canonically (BUCKET_ORDER), then any unknown bucket
    # alphabetical at the end.
    all_buckets = set(music_buckets) | set(sfx_buckets)
    ordered: list[str] = [b for b in BUCKET_ORDER if b in all_buckets]
    extra = sorted(all_buckets - set(BUCKET_ORDER))
    ordered.extend(extra)

    # Render bucket sections first (which applies the keep/wired
    # filter), then build the top-of-page nav from ONLY the buckets
    # that produced non-empty content. Otherwise nav chips would
    # point to empty bucket sections that no longer render.
    rendered_buckets: list[tuple[str, str]] = []  # (bucket, html)
    for bucket in ordered:
        s = _render_bucket_section(
            bucket,
            music_buckets.get(bucket, []),
            sfx_buckets.get(bucket, []),
            review_state, sfx_provenance,
        )
        if s.strip():
            rendered_buckets.append((bucket, s))

    bucket_sections = [html for _, html in rendered_buckets]

    # Top-of-page navigation: one chip per RENDERED bucket. The chip
    # count reflects only items that survived the keep/wired filter
    # (i.e. the work Aaron still has to review in that bucket).
    nav_chips = []
    for bucket, html in rendered_buckets:
        # Count visible music + sfx cards inside the rendered HTML.
        n = html.count('class="music-ctx"') + html.count('class="sfx-item')
        anchor = ("bucket-" + bucket.lower()
                  .replace(" ", "-").replace("(", "").replace(")", "")
                  .replace("—", "").replace("--", "-").replace("/", "-")
                  .strip("-"))
        nav_chips.append(
            f'<a class="nav-chip" href="#{_esc(anchor)}">'
            f'{_esc(bucket)} <span class="nav-count">{n}</span></a>'
        )
    nav_html = '<nav class="bucket-nav">' + "".join(nav_chips) + '</nav>'

    # Count keep+wired items so the summary can show what was filtered.
    n_committed_music = 0
    n_committed_sfx = 0
    for ctx_dir, _m in contexts:
        rev = review_state.get(f"music/{ctx_dir.name}", {}) or {}
        if rev.get("status") in ("keep", "wired"):
            n_committed_music += 1
    for subdir, paths in sfx_groups.items():
        for p in paths:
            rev = review_state.get(f"sfx/{subdir}/{p.stem}", {}) or {}
            if rev.get("status") in ("keep", "wired"):
                n_committed_sfx += 1
    n_committed = n_committed_music + n_committed_sfx

    # Tally what's STILL on the page after filtering.
    visible_music = len(contexts) - n_committed_music
    visible_sfx = sum(len(paths) for paths in sfx_groups.values()) - n_committed_sfx

    summary = (
        f'<div class="summary">'
        f'Showing <strong>{visible_music}</strong> music + '
        f'<strong>{visible_sfx}</strong> SFX awaiting review · '
        f'<strong>{n_committed}</strong> already committed (keep/wired) '
        f'hidden from this page · {len(rendered_buckets)} non-empty buckets'
        f'</div>'
    )

    body = HTML_HEAD + summary + nav_html
    if bucket_sections:
        body += "".join(bucket_sections)
    else:
        body += '<p class="summary">(no audio yet — run audio_generate.py / audio_sfx_generate.py)</p>'
    body += HTML_TAIL

    OUT_PATH.write_text(body, encoding="utf-8")
    return OUT_PATH


if __name__ == "__main__":
    p = build()
    print(f"wrote {p}")
    print()
    print("Serve from the project root:")
    print(f"  cd {ROOT}")
    print("  python -m http.server 8770")
    print("Then open: http://localhost:8770/tools/audio_player.html")
