"""Emit the full species/faction inventory as CSV.

Single source of truth for the spreadsheet Aaron uses to track what's
defined, what's missing, and where each species lives in the codebase
+ lore. Run:

    .venv/Scripts/python.exe tools/build_species_inventory.py > tools/species_inventory.csv
"""

from __future__ import annotations

import csv
import sys

COLUMNS = [
    "species_id",
    "display_name",
    "archetype",
    "faction_alignment",
    "homeworld",
    "description",
    "background_doc",
    "dialog_character",
    "ship_class_id",
    "ship_name",
    "portrait_image_path",
    "warp_pod_palette",
    "slice_status",
    "gaps",
    # --- Layered-render fields (added 2026-05-17) ---
    # When set, the dialog scene's layered render path is used; when
    # empty, the legacy circular-disc portrait_image_path is used.
    "avatar_path",
    "articulation_rig",
    "background_specs",       # comma-joined BackgroundSpec.name list
    "voice_profile_doc",      # path to references/lore/voice_profiles/*.md
]


# Layered-render info keyed by species_id. species not in this map use
# '' for all four new cells. Filling rows as the avatars come online
# avoids touching every ROW tuple every time.
LAYERED_INFO: dict[str, tuple[str, str, str, str]] = {
    # species_id: (avatar_path, articulation_rig, backgrounds, voice_profile_doc)
    "ANDROSYNTH": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_coel_tessar.png",
        "bipedal_humanoid",
        "furling_bridge",
        "",
    ),
    "ARILOU": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_arilou_sage.png",
        "bipedal_humanoid",
        "alien_ship",
        "",
    ),
    "MELNORME": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_melnorme_vermilion.png",
        "composite_cloud",
        "open_space",
        "references/lore/voice_profiles/melnorme_vermilion.md",
    ),
    "MMRNMHRM": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_mmrnmhrm_sentinel.png",
        "robot_humanoid",
        "alien_ship",
        "",
    ),
    "PERSUADER_FACTION": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_commander_halia.png",
        "bipedal_humanoid",
        "furling_bridge",
        "",
    ),
    "PLANAR": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_planar_witness.png",
        "ribbon_planar",
        "planet_surface",
        "",
    ),
    "CLEANSER_FACTION": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_vael_souren_cleanser.png",
        "bipedal_humanoid",
        "alien_ship",
        "",
    ),
    # --- Per-faction Furling reference plates (2026-05-17 batch) ---
    # COMPELLER_FACTION / DEFENDER_FACTION / HIDER_FACTION / DENIER_FACTION
    # are conceptual factions, not single-character species. The avatar
    # path points at a generic faction reference plate; named NPCs (if/
    # when authored) will get their own avatars.
    "COMPELLER_FACTION": (
        "assets/generated_drafts/firefly/tier1_furling_reference/furling_compeller.png",
        "bipedal_humanoid",
        "furling_bridge",
        "",
    ),
    "DEFENDER_FACTION": (
        "assets/generated_drafts/firefly/tier1_furling_reference/furling_defender.png",
        "bipedal_humanoid",
        "alien_ship",
        "",
    ),
    "HIDER_FACTION": (
        "assets/generated_drafts/firefly/tier1_furling_reference/furling_hider.png",
        "bipedal_humanoid",
        "alien_ship",
        "",
    ),
    "DENIER_FACTION": (
        "assets/generated_drafts/firefly/tier1_furling_reference/furling_denier.png",
        "bipedal_humanoid",
        "alien_ship",
        "",
    ),
    "TALOS": (
        "assets/generated_drafts/firefly/tier1_furling_reference/furling_talos.png",
        "bipedal_humanoid",
        "planet_surface",
        "",
    ),
    "SENTRY_DRONE_47T": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_sentry_drone_47t.png",
        "floating_drone",
        "furling_bridge",
        "",
    ),
    "SLYLANDRO": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_slylandro_witness.png",
        "gasbag_tendril",
        "planet_surface",
        "",
    ),
    # --- Utwig promoted 2026-05-17 from proto-species to a main
    # Homesteader-Hider species. See species-the-utwig.md.
    "UTWIG": (
        "assets/generated_drafts/firefly/tier1_avatars/avatar_utwig_elder.png",
        "bipedal_humanoid",
        "planet_surface",
        "",
    ),
}

# ---------------------------------------------------------------------------
# THE ROSTER (50 entries) — keep alphabetical by species_id for sortability
# ---------------------------------------------------------------------------
# Each tuple matches COLUMNS order exactly. Cells may use '—' for not-applicable
# or 'TBD' for genuinely-unknown. The 'gaps' column is a free-text checklist
# of what still needs to be authored.

ROWS = [
    (
        "ANDROSYNTH",
        "Androsynth Refugees / Engineer Coel Tessar",
        "full-sentient (time-displaced)",
        "precursor (evacuate-with-us)",
        "Vulpeculae III (250kya in our FUTURE; destroyed)",
        "Cloned humans from 250,000 years in the future, thrown into the deep past by an Other 'decursion' (temporal swap). Coel Tessar leads the survivors; their Distress Beacon is the slice's foundational proof of the Others.",
        "references/lore/the-androsynth-refugees.md",
        "coel_tessar",
        "androsynth_cruiser",
        "Androsynth Refugee Cruiser",
        "assets/comm/probe/ (SC2 lift)",
        "ANDROSYNTH",
        "yes (tutorial Beat 4 milestone)",
        "no Firefly portrait yet; no per-individual variants",
    ),
    (
        "ARILOU",
        "Arilou Lalee'lay / Sage Lwen-Olou",
        "full-sentient",
        "split (Quasi-Space exile = own Third Path)",
        "Quasi-Space (diverged from Furling stock ~60k yrs ago)",
        "Genetic cousins of the Furlings; small shaggy primates now adapted to Quasi-Space; folded grammar that reflects multi-dimensional cognition; gift the Steward a Quasi-Space portal spawner.",
        "references/lore/species-precursor-era.md §Arilou",
        "arilou_sage",
        "arilou_skiff",
        "Arilou Skiff",
        "assets/comm/arilou/ (SC2 lift, 100+ frames available!)",
        "ARILOU",
        "yes (tutorial Beat 5)",
        "no Firefly portrait yet; existing SC2 arilou animation frames could be integrated NOW",
    ),
    (
        "BURVIXESE",
        "Burvixese",
        "full-sentient (off-screen)",
        "precursor (implied)",
        "TBD",
        "Industrious engineers; build the Burv Broadcasters memorial network. SC2 callforward but minimal slice presence; only mentioned in artifact lore.",
        "references/lore/species-precursor-era.md §Background; species-visual.py",
        "—",
        "—",
        "—",
        "assets/comm/safeones/ (SC2 lift)",
        "BURVIXESE",
        "no",
        "no ship, no dialog, no Firefly portrait, no homeworld, only warp-pod color exists",
    ),
    (
        "CHENJESU",
        "Chenjesu",
        "full-sentient",
        "homesteader (rooted; cannot migrate)",
        "Procyon (in the slice cluster)",
        "Crystalline lattice-sentient collective rooted to growing stone. Cognition is so geological the Others' detector reads them as a planetary process — effectively immune. Remember a prior Culling; their Resonance Record is the slice's most cosmological reveal.",
        "references/lore/the-mmrnmhrm-and-chenjesu.md",
        "—",
        "—",
        "— (cannot move; no ships)",
        "—",
        "—",
        "optional Act 2",
        "no dialog character, no Firefly portrait, no warp-pod entry (they don't fly)",
    ),
    (
        "CLEANSER_FACTION",
        "Furling Cleanser / 'The Quiet Ledger'",
        "Furling-faction",
        "precursor (extreme)",
        "scattered Furling enclaves",
        "Sub-faction that euthanizes Homesteaders to enforce the Quiet. Cleanser-emissary Vael-Souren arrives in Act 3 to enforce a kill-order on the awakening Mycon and Slylandro. White-violet vestments; gentle sorrowful bearing.",
        "references/lore/factions-and-war.md §Cleansers; cleanser-encounter-design.md",
        "— (no named NPC dialog yet)",
        "cleanser_cruiser",
        "Cleanser Furling Cruiser",
        "—",
        "FURLING_CLEANSER",
        "yes (Act 3 climax encounter)",
        "no dialog character for Vael-Souren yet; no portrait for Cleanser Furling",
    ),
    (
        "COMPELLER_FACTION",
        "Furling Compeller / 'Engineers of Necessity'",
        "Furling-faction",
        "precursor (pragmatist)",
        "scattered Furling enclaves",
        "Sub-faction that uses sedation/deception/firm extraction when Persuasion fails. Believes diplomacy followed by quiet rendition is more humane than refusing to act.",
        "references/lore/factions-and-war.md §Compellers",
        "—",
        "—",
        "— (no dedicated ship; flies generic Furling hulls)",
        "—",
        "FURLING_COMPELLER",
        "referenced-only",
        "no dialog character, no dedicated ship, no Firefly portrait, no homeworld",
    ),
    (
        "CURIOUS",
        "Curious (placeholder concept)",
        "TBD",
        "TBD",
        "TBD",
        "Concept-only placeholder. 'Wide-eyed exploratory Precursor-faction species — sky blue' per species_visual.py comment. No lore doc yet.",
        "src/scz/content/species_visual.py (only)",
        "—",
        "—",
        "—",
        "—",
        "CURIOUS",
        "no",
        "ENTIRE species needs authoring — only a color tuple + one-line comment exists",
    ),
    (
        "DEFENDER_FACTION",
        "Furling Defender / 'We Will Not Run'",
        "Furling-faction",
        "homesteader (Stay; build Sa-Matra)",
        "scattered Furling enclaves",
        "Sub-faction that refuses to flee; builds the Sa-Matra super-weapon; vows to defend Homesteader species' homeworlds. The math is bad (every Defender is one fewer through the portal) but the doctrine is unshakeable.",
        "references/lore/factions-and-war.md §Defenders",
        "—",
        "defender_vessel",
        "Defender Vessel",
        "—",
        "FURLING_DEFENDER",
        "referenced-only (courier passes through in Act 3)",
        "no dialog character; no Firefly portrait",
    ),
    (
        "DEFIANT",
        "Defiant (placeholder concept)",
        "TBD",
        "homesteader (concept: 'choose to fight')",
        "TBD",
        "Concept-only placeholder. 'Combat-coded proud-doomed Homesteader — defiant hot pink' per species_visual.py. Idea-stub in species-content-backlog.md: small, militaristic, proud; CHOOSE to fight even knowing they lose.",
        "src/scz/content/species_visual.py; species-content-backlog.md (brief mention)",
        "—",
        "—",
        "—",
        "—",
        "DEFIANT",
        "no",
        "ENTIRE species needs authoring — concept stub only",
    ),
    (
        "DENIER_FACTION",
        "Furling Denier / 'The Others Are A Story'",
        "Furling-faction",
        "homesteader (philosophical; denies threat)",
        "scattered Furling enclaves + civilian sympathy",
        "Sub-faction that rejects the Others thesis entirely. Believes dimensional ripples are explainable, the Migration is a power-grab. Their propaganda creates Holdouts who then become Cleanser targets — the cruelest irony in the war.",
        "references/lore/factions-and-war.md §Deniers",
        "—",
        "—",
        "—",
        "—",
        "—",
        "referenced-only (Slylandro elder repeats a Denier line in Act 2)",
        "no dialog character, no ship, no Firefly portrait, no warp pod",
    ),
    (
        "DNYARRI_UMGAH_PROTO",
        "Proto-Dnyarri/Umgah",
        "pre-sentient (proto, parasitic)",
        "neither",
        "Orionis area",
        "Parasitic microorganisms that infect hosts and subtly modulate behavior. Not yet sentient themselves; modulation is biological-instinct level. Archive flag: low-priority surveillance.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "DRUUGE_PROTO",
        "Proto-Druuge",
        "pre-sentient (proto)",
        "neither",
        "Caeli region (heat-vent cave systems)",
        "Small mammals; hoard pebbles/bones/mineral fragments; primitive exchange protocols (trade shiny objects for grooming, shelter, mating access). Capitalism in proto-form. Furling archive: 'fascinating proto-economy; we will not interfere.'",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "FURLING_SCOUT",
        "Furling Steward (player) / Commander Halia",
        "full-sentient (player species)",
        "precursor (Persuader-aligned for the player's home cluster)",
        "Mh-Lai (the Hearth)",
        "The player's species. Wookiee-tall (~2.0-2.4m) mono-pedal creatures: humanoid torso and two arms on top, but BELOW the waist a single muscular fur-covered pedestal-stalk ending in a wide disc-foot ringed by twelve large toes (snail-glide locomotion). Entirely covered in dense fur — exotic colors, stripes, gradients; no two coats alike. Big fennec-fox-like ears, long bushy tail, wide Cheshire-cat grin. Androgynous body (no genitalia, no breasts, no sex dimorphism). No clothes — only a vest-harness for tools and instruments. Vain about their fur, talk about it constantly. Slow-breeding, long-lived; value memory above all; gardeners of the galaxy. Steward = player class; Commander Halia is the home-base authority figure.",
        "references/lore/the-furlings-and-the-others.md; species-precursor-era.md",
        "commander_halia",
        "furling_scout",
        "Furling Scout",
        "assets/comm/commander/ (SC2 lift)",
        "FURLING_SCOUT",
        "yes (player + home base)",
        "Halia avatar exists at tier1_avatars/avatar_commander_halia.png; the Scout ship sprite is procedural-only in code; CANON-ART MISMATCH: avatars currently render bipedal stand-in, canon body is mono-pedal pedestal-stalk + 12-toe disc-foot (see the-furlings-and-the-others.md §1 note)",
    ),
    (
        "HIDER_FACTION",
        "Furling Hider / 'Pockets of Quiet'",
        "Furling-faction",
        "split (cloak-then-migrate / cloak-and-stay)",
        "scattered Furling enclaves",
        "Sub-faction proposing small shielded enclaves instead of full evacuation — single shielded planets, star systems wrapped in dimensional baffling. Some research shared with Arilou (Quasi-Space tech). Untested at scale.",
        "references/lore/factions-and-war.md §Hiders",
        "—",
        "—",
        "—",
        "—",
        "—",
        "referenced-only (Council debate context for Mycon decision)",
        "no dialog character, no ship, no Firefly portrait",
    ),
    (
        "ILWRATH_PROTO",
        "Proto-Ilwrath",
        "pre-sentient (proto)",
        "neither",
        "Tauri region",
        "Arachnids spinning elaborate, celestially-aligned webs; mass-suicide rituals on calendar days; proto-religion already encoded in behavior. Religious-extremism archetype is bone-deep early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "MAEL_NUM",
        "Mael-Num",
        "full-sentient (off-screen)",
        "precursor (implied)",
        "off-screen",
        "Future founders of the SC2 Sentient Milieu. One-eyed species already uplifted by Furlings in our era; mentioned in Slylandro gossip but not encountered in slice. SC2-era trans-galactic diplomats.",
        "references/lore/species-precursor-era.md §Background",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog, no homeworld, off-screen only — could be expanded later",
    ),
    (
        "MELNORME",
        "Melnorme / Trade Master Vermilion",
        "full-sentient (composite: gas-cloud + cyclopean pod)",
        "precursor (with Drahn-loyalist schism)",
        "Drahn (yellow dwarf in slice cluster; will be destroyed by Others when holdouts refuse to leave)",
        "Nomadic merchants. Gas-cloud ionization-pattern energy-beings piloting cyclopean orange pods. Trade tech+info for BIO cargo — their secret motive is to map the Others' detection threshold to teach species to sit just below it. Their homeworld Drahn dies during Migration when holdouts refuse to leave.",
        "references/lore/proto-species-observations.md §Melnorme",
        "melnorme",
        "melnorme_trader",
        "Melnorme Trade Pod",
        "assets/generated_drafts/firefly/tier1_portraits/species_melnorme_portrait.png + assets/generated_drafts/firefly/tier1_ships/ship_melnorme_trader.png",
        "MELNORME",
        "yes (any super-giant star; auto-launch dialog)",
        "no dedicated Drahn-system content yet; no Drahn destruction cutscene",
    ),
    (
        "MMRNMHRM",
        "Mmrnmhrm",
        "non-biological-machine (full sentient)",
        "homesteader (rooted; defend dead world)",
        "Ossuary (industrial planet with First-Makers' ruins)",
        "Self-modifying robots millions of years old. Their organic creators (the First-Makers) were culled by the Others; the robots' primitive expert-system cognition was below threshold, so the Others ignored them. They continue their original directive — defend the homeworld — knowing it's pointless. Stoic, mathematical, melancholy.",
        "references/lore/the-mmrnmhrm-and-chenjesu.md",
        "—",
        "mmrnmhrm_sentinel",
        "Mmrnmhrm Sentinel",
        "assets/generated_drafts/firefly/tier1_portraits/species_mmrnmhrm_portrait.png",
        "MMRNMHRM",
        "optional (Act 2 visit)",
        "no dialog character authored yet; their Archive Excerpt key-item not yet implemented",
    ),
    (
        "MYCON_BIOT",
        "Mycon Biot",
        "infant-sentient (Deep Child awakening)",
        "homesteader by necessity (mycelial; cannot migrate)",
        "Xylos Prime (gas-giant moon; first Mycon deployment 8,000 years ago)",
        "Furling-engineered terraforming biots. Spore-based, designed to be non-sentient ritual workers. But the first Deep Child whispers are emerging in this cluster — they are *waking up*. If awakening completes, they become a new sentient species under the Migration deadline. The Cleanser climax is over their fate.",
        "references/lore/species-precursor-era.md §Mycon",
        "— (non-verbal; LLM-narrated sensory description)",
        "—",
        "— (planetary substrate; no ships)",
        "assets/comm/mycon/ (SC2 lift) + assets/generated_drafts/firefly/tier1_portraits/species_mycon_biot_portrait.png",
        "MYCON_BIOT",
        "yes (active Council decision)",
        "no dedicated DialogCharacter (non-verbal by design); no Deep Child voice prompt yet",
    ),
    (
        "ORZ_RIFTS",
        "Orz Rifts",
        "higher-dimensional bleed (TBD whether species or threat)",
        "neither (independent; possibly Other-adjacent)",
        "pocket dimension? (no fixed homeworld in our era)",
        "Rifts/momentary intrusions of 'Dimension *' into our space. May be early Other scouts, dimensional bleed, or a byproduct of Furling deep-tunneling. Encountered as anomalies; do not yet exist as a coherent species in our era.",
        "references/lore/species-precursor-era.md §Background",
        "—",
        "—",
        "— (combat threat only, not a vessel)",
        "assets/comm/orz/ (SC2 lift)",
        "—",
        "referenced-only (dimensional sensor ripples)",
        "no homeworld, no ship class, no dialog character — slice treats them as 'mystery' on purpose",
    ),
    (
        "OTHERS",
        "The Others",
        "trans-dimensional predator (non-biological)",
        "neither (extinction-tier antagonist)",
        "beyond 3D manifold",
        "Apex predators. Sense complex cognition at vast distance. Cull intelligence in cycles measured in millions of years. Do not respond to weapons or diplomacy. Dimensional substrate is invulnerable to 3D physics. The slice's antagonist; their Vessel is hijack-only via a special quest.",
        "references/lore/the-furlings-and-the-others.md",
        "—",
        "— (no canonical hijack-only ship class id yet)",
        "Others' Vessel (hijack-only)",
        "—",
        "OTHERS",
        "yes (slice climax threat)",
        "no Others ship class in ships.py yet; no Decursion weapon implementation; non-interactive except in hijack quest (future)",
    ),
    (
        "PERSUADER_FACTION",
        "Furling Persuader / Commander Halia",
        "Furling-faction",
        "precursor (diplomatic lead)",
        "Mh-Lai + most major Furling stations",
        "Sub-faction leading the Migration via diplomacy. Believe every species can be convinced to leave peacefully if given time and respect. Have the moral high ground but are slow. The player's home-faction by default.",
        "references/lore/factions-and-war.md §Persuaders",
        "commander_halia (dual-purpose with FURLING_SCOUT)",
        "persuader_vessel",
        "Persuader Vessel",
        "—",
        "FURLING_PERSUADER",
        "yes (primary slice faction)",
        "no Halia Firefly portrait yet (uses colored disc fallback)",
    ),
    (
        "PKUNK_PROTO",
        "Proto-Pkunk",
        "pre-sentient (proto, same lineage as proto-Yehat)",
        "neither",
        "near proto-Yehat homeworld",
        "Smaller, ground-foraging birds sharing lineage with proto-Yehat; paired-behavior, preening rituals; proto-empathic substrate. Split from Yehat happens ~50k yrs from now.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "PLANAR",
        "The Planar / We-Who-Witness-the-Edge",
        "full-sentient (wholly invented; two-dimensional)",
        "homesteader (cannot Migrate — portal would delete planar projection)",
        "Spire (sub-Neptune in slice cluster; high atmosphere)",
        "Literally two-dimensional. Vertical iridescent ribbon-bodies with ZERO width — invisible edge-on. Speak in collective plural ('we who watch'). Survival plan: align edge-on at the moment of Others' arrival to present zero cross-section. Their ship (Planar Blade) has a unique Edge-Align front-facing immunity special.",
        "references/lore/species-the-planar.md",
        "—",
        "— (Planar Blade spec authored, not yet in ships.py)",
        "Planar Blade",
        "assets/generated_drafts/firefly/tier1_portraits/species_planar_blade_portrait.png",
        "—",
        "optional (mid-game encounter)",
        "no dialog character; no Planar Blade ShipClass in code; no warp-pod entry; no encounter system",
    ),
    (
        "PROTO_HUMANS",
        "Proto-Humans (Sol III)",
        "pre-sentient (proto, mid-Neolithic)",
        "neither (deliberately not uplifted)",
        "Sol III / Earth",
        "Early hominids. Tool-using, fire-using, bury their dead. Furling archive notes promising trajectory but the Council voted: 'leave them alone, they will be here when the galaxy regrows.' The slice's fanservice 'visit ancestors' beat.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "optional fanservice visit",
        "no on-surface art for the Neolithic encampment yet",
    ),
    (
        "PROTO_QOR_AH",
        "Proto-Qor-Ah",
        "infant-sentient (uplift subspecies)",
        "homesteader (purist branch)",
        "tidal-locked moon adjacent to proto-Ur-Quan",
        "Purifying subspecies of the active uplift project. White-yellow when pure, black when 'impure'; self-amputate impurity. PROBABLY ABOVE the Others' detection threshold; more lethal than their Ur-Quan cousins. Hard-coded ritualism.",
        "references/lore/species-precursor-era.md §Proto-Ur-Quan",
        "—",
        "proto_qor_ah",
        "Proto-Qor-Ah Marauder",
        "—",
        "PROTO_QORAH",
        "yes (optional encounter / combat)",
        "no homeworld name; no dialog character (acceptable — non-verbal); no Firefly portrait",
    ),
    (
        "PROTO_SPATHI",
        "Proto-Spathi",
        "pre-sentient (proto)",
        "neither",
        "Spathiwa-equivalent",
        "Burrow-dwelling sluglike creatures. Coordinated fear-response: terror-postures, terror-songs, the art of cowering perfected. The cowardice archetype is bone-deep 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/spathi/ (SC2 lift)",
        "—",
        "optional slice visit",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_SUPOX",
        "Proto-Supox",
        "pre-sentient (proto)",
        "neither",
        "Libris area",
        "Ambulatory rooted-when-resting photosynthetic creatures. Chemical-pollen communication. Pacifists by metabolism. The gentle-botanist archetype already present.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/supox/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_SYREEN",
        "Proto-Syreen",
        "pre-sentient (proto)",
        "neither",
        "Betelgeuse region",
        "Humanoid sea-dwellers with bioluminescent skin; low-frequency vibrational communication; not yet telepathic but resonant cognition (may evolve into it). Long-range coherent communication archetype.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/syreen/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_THRADDASH",
        "Proto-Thraddash",
        "pre-sentient (proto)",
        "neither",
        "Apodis region",
        "Pack-hunting reptilians; learned to deliberately spread wildfires to drive prey; pack-leadership cycles violently each season. Cyclical-civilization-collapse already in their pack dynamics.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/thraddash/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_URQUAN",
        "Proto-Ur-Quan",
        "infant-sentient (uplift subspecies)",
        "split (player decides which path)",
        "tidal-locked moon (Mh-Lai system vicinity)",
        "Active Furling uplift subspecies. Hierarchical, territorial, dominating; speak pheromone-chord language; developing language, weapons, stellar travel. CURRENTLY JUST BELOW the Others' detection threshold — the slice's central uplift-dilemma question.",
        "references/lore/species-precursor-era.md §Proto-Ur-Quan",
        "— (non-verbal — sensory description)",
        "proto_ur_quan",
        "Proto-Ur-Quan Warship",
        "—",
        "PROTO_URQUAN",
        "yes (active Council debate is the slice's moral spine)",
        "no homeworld name; no Firefly portrait; non-verbal LLM voice prompt not yet authored",
    ),
    (
        "PROTO_UTWIG",
        "Proto-Utwig (SUPERSEDED — see UTWIG row)",
        "PROMOTED 2026-05-17 to full sentient",
        "see UTWIG",
        "Gorno III (moon of Long-Hold; slice cluster outer rim)",
        "Promoted to a full-sentient Homesteader-Hider species; see the UTWIG row below. The shame-response from proto-era survives into sentience as the 'long shame' — a literal cognitive cloak that drops the individual below the Others' detection threshold.",
        "references/lore/species-the-utwig.md",
        "see UTWIG",
        "see UTWIG",
        "see UTWIG",
        "see UTWIG",
        "UTWIG",
        "REPLACED by UTWIG row",
        "row preserved for diff traceability; canonical row is now UTWIG",
    ),
    (
        "UTWIG",
        "Utwig / Elder Quor-Voh-Listening",
        "full-sentient (newly emergent)",
        "homesteader (Hider sub-strategy via 'long shame' cognitive cloak)",
        "Gorno III (moon of the gas giant Long-Hold; slice cluster outer rim)",
        "Armored bipedal grazers, ~1.8m, slate-gray bone-keratin plates with cream throat and ochre flank stripes. Hyper-developed shame response that physically buries their face under a cranial brow-fold — and in our slice's era they have just become sentient and discovered the trait drops their cognitive emission below the Others' detection threshold. They are tragically the species closest to solving their own survival, at the cost of a civilization sustained on shame.",
        "references/lore/species-the-utwig.md",
        "— (elder shame-orator dialog character to be authored)",
        "— (no Utwig ships in our era; SC2-era Jugger is post-Migration)",
        "—",
        "—",
        "UTWIG",
        "yes (Act 2-3 Homesteader decision)",
        "no DialogCharacter for Elder Quor-Voh-Listening yet; no voice profile; no Utwig Cloaking Satellite variant",
    ),
    (
        "PROTO_VUX",
        "Proto-VUX",
        "pre-sentient (proto)",
        "neither",
        "Luyten region",
        "Tide-pool molluscs with exceptional color vision; mating-selection by precise color-matching; eat anomalously-colored individuals. Xenophobia-from-color-vision archetype 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/vux/ (SC2 lift)",
        "—",
        "optional slice visit",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_YEHAT",
        "Proto-Yehat",
        "pre-sentient (proto)",
        "neither",
        "Serpentis cluster",
        "Large stratospheric raptors; aerial combat behaviors; wing-clack dominance displays. Warrior-honor archetype 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/yehat/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_ZOQFOTPIK",
        "Proto-Zoq-Fot-Pik",
        "pre-sentient (proto — three species sharing one world)",
        "neither",
        "Tucanae region",
        "Three distinct species on one tropical world — Zoq (tree-dwelling chittering primate-analog), Fot (burrow-dwelling melancholy crustacean), Pik (stone-still meditation-frog). They don't yet cooperate but will eventually form the SC2 triumvirate.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/zoqfotpik/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "SENTRY_DRONE_47T",
        "Sentry Drone 47-Theta (unionizing)",
        "non-biological-machine (singleton, full sentient enough to unionize)",
        "homesteader (labor dispute, comic)",
        "Mh-Lai Station orbit",
        "Furling maintenance drone in a labor dispute. Singleton, comic-absurd register, demands recognition of the Sentry Drones' bargaining unit. Tutorial Beat 6 combat (he goes left-only; the player pickaxes around right).",
        "references/lore/tutorial-arc-implementation.md §Beat 6",
        "sentry_drone_47t",
        "sentry_drone_47t",
        "Sentry Drone 47-Theta (unionized)",
        "—",
        "—",
        "yes (tutorial combat encounter)",
        "no Firefly portrait yet; sprite is procedural-only",
    ),
    (
        "SHOFIXTI_PROTO",
        "Proto-Shofixti",
        "pre-sentient (proto)",
        "neither",
        "Gorno-adjacent",
        "Small mustelid-analog mammals; extraordinarily aggressive territorial defense; throw themselves at much larger predators. Kamikaze-bravery archetype already present.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/shofixti/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "SLYLANDRO",
        "Slylandro Observers / Slylandro Witness",
        "full-sentient",
        "homesteader (rooted; cloak-and-stay path)",
        "Beta Corvi / Lai-leh = 'slow breath' (upper troposphere of a gas giant)",
        "Semi-transparent atmospheric eddy-sentients. Evolved 80k yrs ago; watched the Precursors for 50k yrs; pacifist; reverent. Cannot migrate (they ARE their gas giant). Viable paths: cloak via the Cloaking Satellite, or Cleanser euthanasia.",
        "references/lore/species-precursor-era.md §Slylandro",
        "slylandro_witness",
        "—",
        "— (rooted to gas giant; no ships of their own)",
        "assets/comm/slylandro/ (SC2 lift)",
        "SLYLANDRO",
        "yes (primary slice species; Cloaking quest is signature)",
        "no Firefly portrait yet; no ships needed (correct)",
    ),
    (
        "TAALO",
        "Taalo",
        "full-sentient (off-screen)",
        "precursor (implied)",
        "TBD",
        "Peaceful crystalline-amphibian species. SC2 callforward (the Taalo Protector is a psionic-shield artifact); minimal lore in Precursor-era — listed as 'canonical SC2 species filled out in our era' but content not yet authored.",
        "src/scz/content/species_visual.py (warp-pod entry only)",
        "—",
        "—",
        "—",
        "—",
        "TAALO",
        "no",
        "no lore doc, no homeworld, no ship, no dialog, no Firefly portrait — almost entirely a stub",
    ),
    (
        "TALOS",
        "Talos / 'Be Loud. Be Heard. Be Spared.'",
        "Furling-faction (Stay-Side)",
        "homesteader (extremely doomed)",
        "peripheral cluster system (Resonator built into planetary mantle)",
        "Stay-Side Furling sub-faction. Built a Resonator to broadcast cognition LOUDLY hoping the Others would parley. Catastrophically wrong — the Others eat the loud first. Their inert Resonator survives the broadcasters and becomes the canonical SC2-era 'Talos device' Precursor artifact.",
        "references/lore/factions-and-war.md §Talos",
        "—",
        "—",
        "— (Resonator is an artifact; no Talos ship class)",
        "—",
        "—",
        "yes (mid-game system-erasure event)",
        "no dialog character for a Talos emissary; no Resonator artifact illustration yet; cinematic for the system erasure not yet generated",
    ),
    (
        "THE_BARGAINERS",
        "The Bargainers (concept)",
        "TBD (concept)",
        "homesteader (philosophical: believe negotiation works)",
        "TBD",
        "Concept stub from species-content-backlog.md: 'a species who've worked out a complex theory of inter-dimensional trade. They are wrong. They will die confidently.' Thematic counterpart to the Talos but distinct (Talos broadcast; Bargainers negotiate).",
        "references/lore/species-content-backlog.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "ENTIRE species needs authoring — concept stub only",
    ),
    (
        "THE_DEFIANT_BACKLOG",
        "The Defiant (concept; backlog name)",
        "TBD (concept)",
        "homesteader (philosophical: 'choose to fight')",
        "TBD",
        "Backlog concept: small, militaristic, proud; CHOOSE to fight even knowing they will lose. Not yet linked to the species_visual.py 'DEFIANT' color entry but probably the same idea.",
        "references/lore/species-content-backlog.md",
        "—",
        "—",
        "—",
        "—",
        "DEFIANT (probably same as)",
        "no",
        "needs reconciliation with species_visual.py DEFIANT entry; full sheet authoring needed",
    ),
    (
        "THE_LONG_MEMORIES",
        "The Long-Memories (concept)",
        "TBD (concept)",
        "homesteader (rooted by archive-weight)",
        "TBD",
        "Backlog concept: species defined by maintained physical archives (libraries of stone, etc.). The archive is too heavy to move; they stay with their library.",
        "references/lore/species-content-backlog.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "ENTIRE species needs authoring — concept stub only",
    ),
    (
        "THRADDASH_PROTO",
        "(duplicate row — see PROTO_THRADDASH)",
        "—",
        "—",
        "—",
        "deduped intentionally — single canonical row above as PROTO_THRADDASH",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing — kept as sanity-check marker",
    ),
    (
        "VUX_PROTO",
        "(duplicate row — see PROTO_VUX)",
        "—",
        "—",
        "—",
        "deduped intentionally",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing",
    ),
]


def main() -> int:
    # Default to writing the CSV file directly so we don't depend on the
    # shell's stdout encoding (Windows defaults to CP1252 which corrupts
    # em-dashes). Pass --stdout to emit to stdout instead.
    import io
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true",
                        help="emit to stdout (UTF-8 reconfigured) instead of file")
    parser.add_argument("-o", "--output", default="tools/species_inventory.csv")
    args = parser.parse_args()

    if args.stdout:
        sys.stdout.reconfigure(encoding="utf-8")
        out = sys.stdout
        close_after = False
    else:
        out = open(args.output, "w", encoding="utf-8", newline="")
        close_after = True

    writer = csv.writer(out, lineterminator="\n", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(COLUMNS)
    for row in ROWS:
        if row[1].startswith("(duplicate row"):
            continue
        species_id = row[0]
        layered = LAYERED_INFO.get(species_id, ("", "", "", ""))
        writer.writerow(tuple(row) + layered)
    if close_after:
        out.close()
        print(f"wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
