"""Emit the full species/faction inventory as CSV.

Single source of truth for the spreadsheet Aaron uses to track what's
defined, what's missing, and where each species lives in the codebase
+ lore. Run:

    .venv/Scripts/python.exe tools/build_species_inventory.py > tools/species_inventory.csv
"""

from __future__ import annotations

import csv
import sys

COLUMNS = [
    "species_id",
    "display_name",
    "archetype",
    "faction_alignment",
    "homeworld",
    "description",
    "background_doc",
    "dialog_character",
    "ship_class_id",
    "ship_name",
    "portrait_image_path",
    "warp_pod_palette",
    "slice_status",
    "gaps",
]

# ---------------------------------------------------------------------------
# THE ROSTER (50 entries) — keep alphabetical by species_id for sortability
# ---------------------------------------------------------------------------
# Each tuple matches COLUMNS order exactly. Cells may use '—' for not-applicable
# or 'TBD' for genuinely-unknown. The 'gaps' column is a free-text checklist
# of what still needs to be authored.

ROWS = [
    (
        "ANDROSYNTH",
        "Androsynth Refugees / Engineer Coel Tessar",
        "full-sentient (time-displaced)",
        "precursor (evacuate-with-us)",
        "Vulpeculae III (250kya in our FUTURE; destroyed)",
        "Cloned humans from 250,000 years in the future, thrown into the deep past by an Other 'decursion' (temporal swap). Coel Tessar leads the survivors; their Distress Beacon is the slice's foundational proof of the Others.",
        "references/lore/the-androsynth-refugees.md",
        "coel_tessar",
        "androsynth_cruiser",
        "Androsynth Refugee Cruiser",
        "assets/comm/probe/ (SC2 lift)",
        "ANDROSYNTH",
        "yes (tutorial Beat 4 milestone)",
        "no Firefly portrait yet; no per-individual variants",
    ),
    (
        "ARILOU",
        "Arilou Lalee'lay / Sage Lwen-Olou",
        "full-sentient",
        "split (Quasi-Space exile = own Third Path)",
        "Quasi-Space (diverged from Furling stock ~60k yrs ago)",
        "Genetic cousins of the Furlings; small shaggy primates now adapted to Quasi-Space; folded grammar that reflects multi-dimensional cognition; gift the Steward a Quasi-Space portal spawner.",
        "references/lore/species-precursor-era.md §Arilou",
        "arilou_sage",
        "arilou_skiff",
        "Arilou Skiff",
        "assets/comm/arilou/ (SC2 lift, 100+ frames available!)",
        "ARILOU",
        "yes (tutorial Beat 5)",
        "no Firefly portrait yet; existing SC2 arilou animation frames could be integrated NOW",
    ),
    (
        "BURVIXESE",
        "Burvixese / Velmek-Resonant-Forty-Three, Caster-Foreman",
        "full-sentient (slice species — Authored 2026-05-17; mostly Eliminated in slice outcome)",
        "homesteader (Be-Loud doctrine; doomed)",
        "Burvix Caster (in stars.json at line 238) — homeworld literally named after the device they are building",
        "Industrious four-armed humanoid engineers. Upper-arm pair: delicate tool-work; lower pair: load-bearing. Two-section toolbelt is identity, not gear (mixing is taboo). Committed to the BE-LOUD DOCTRINE — they reason that broadcasting their cognition at unprecedented amplitude will make the Others recognize them as peers (or pass over them as too costly). They build the Burv Caster — a planetary-scale cognitive-amplification array — as the flagship of this project. Smaller Burv Broadcasters across the galaxy are amplifier-nodes. The Furling Council advised against it; the Burvixese had polite engineer's reasoning for every objection; the Council respected their autonomy. THE DOCTRINE FAILS — the Others arrive faster, eat the loud first. Most Burvixese die at the Caster site within minutes of harmonic activation. A small surviving contingent (whoever was off-world during activation) migrates to Andromeda. The SC2-canonical 'Burvixese are extinct, broadcasters scattered' traces directly to this loss.",
        "references/lore/species-sheets.md §10; species-quests.md 'The Caster Reckoning'; furling-artifacts-and-callforwards.md 'The Burvixese and the Caster' + 'The Burv Broadcasters'",
        "—",
        "—",
        "— (no combat ship — Be-Loud doctrine consumes all engineering capacity; surviving migrants reach Andromeda via Furling lift)",
        "assets/comm/safeones/ (SC2 lift)",
        "BURVIXESE",
        "yes (mid-game catastrophic-witness beat — the Caster's harmonic activation, the failure that follows, optional pre-activation evacuation advocacy)",
        "NEEDS: Firefly portrait (four-armed humanoid in toolbelt; confidence pre-activation, anguish post-failure — TWO portraits to show both states); cinematic for the Caster harmonic activation + the Others' arrival + the system going silent; dialog character for the engineer-foreman; visual design for the Caster array itself (planetary-scale, twelve-cycle build-out, deep-violet carrier-band)",
    ),
    (
        "CHENJESU",
        "Chenjesu / Far-Memory-Spire-Of-The-South-Reef",
        "full-sentient",
        "homesteader (rooted; cannot migrate)",
        "Procyon (in the slice cluster)",
        "Crystalline lattice-sentient collective rooted to growing stone. Cognition is so geological the Others' detector reads them as a planetary process — effectively immune. Remember a prior Culling; their Resonance Record is the slice's most cosmological reveal.",
        "references/lore/the-mmrnmhrm-and-chenjesu.md",
        "—",
        "—",
        "— (cannot move; no ships)",
        "—",
        "—",
        "optional Act 2",
        "no dialog character, no Firefly portrait, no warp-pod entry (they don't fly)",
    ),
    (
        "CLEANSER_FACTION",
        "Furling Cleanser / 'The Quiet Ledger'",
        "Furling-faction",
        "precursor (extreme)",
        "scattered Furling enclaves",
        "Sub-faction that euthanizes Homesteaders to enforce the Quiet. Cleanser-emissary Vael-Souren arrives in Act 3 to enforce a kill-order on the awakening Mycon and Slylandro. White-violet vestments; gentle sorrowful bearing.",
        "references/lore/factions-and-war.md §Cleansers; cleanser-encounter-design.md",
        "— (no named NPC dialog yet)",
        "cleanser_cruiser",
        "Cleanser Furling Cruiser",
        "—",
        "FURLING_CLEANSER",
        "yes (Act 3 climax encounter)",
        "no dialog character for Vael-Souren yet; no portrait for Cleanser Furling",
    ),
    (
        "COMPELLER_FACTION",
        "Furling Compeller / 'Engineers of Necessity'",
        "Furling-faction",
        "precursor (pragmatist)",
        "scattered Furling enclaves",
        "Sub-faction that uses sedation/deception/firm extraction when Persuasion fails. Believes diplomacy followed by quiet rendition is more humane than refusing to act.",
        "references/lore/factions-and-war.md §Compellers",
        "—",
        "—",
        "— (no dedicated ship; flies generic Furling hulls)",
        "—",
        "FURLING_COMPELLER",
        "referenced-only",
        "no dialog character, no dedicated ship, no Firefly portrait, no homeworld",
    ),
    (
        "CURIOUS",
        "(duplicate row — renamed 2026-05-17 to LEMMKIN, see LEMMKIN row)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "LEMMKIN",
        "Lemmkin / Brisk-Ever-Onward (elder) + Snip / Pip / Trill / Yipp (canonical rank-and-file names)",
        "full-sentient (anthropomorphic squirrels; ~1.1m bipedal; large eyes; prehensile tail; canonically fearless)",
        "homesteader (Stay-Side, by CHOICE — they could migrate, they decline, they want to *see what happens*)",
        "Whirligig (densely forested terrestrial world in slice cluster; ~6-hour day; canopy cities built into kilometer-tall trees)",
        "Recklessly curious anthropomorphic squirrels with **NO FEAR** (vestigial amygdala-equivalent — canonically confirmed by Furling neurology). High scientific output, high cliff-mortality. Lemming-clade behavior: when one investigates something, the troupe swarms it, sometimes off the same cliff. Voice: high-pitched, fast cadence, chittery, frequent self-interruption, rising-tone interrogatives. **Pre-Culling archive dispersal canon**: aware they cannot survive, they distribute scientific archives across the galaxy; SC2-era 'Precursor data caches' are canonically Lemmkin archives misattributed. Terminal: Eliminated (with full awareness and consent — they die *learning*).",
        "references/lore/species-the-lemmkin.md",
        "TODO_AVATAR: Brisk-Ever-Onward (Lemmkin elder) + Snip (rank-and-file scientist)",
        "lemmkin_skitter",
        "Lemmkin Skitter (small fast glass cannon with Burst-Scatter Probe primary + Tail-Drop 180-pivot special)",
        "TODO Image chat: Lemmkin portrait + Whirligig planet surface + Lemmkin Skitter exterior",
        "LEMMKIN",
        "yes (optional encounter; quest_id lemmkin_curiosity in tools/quest_inventory.csv)",
        "no portrait yet (Image HANDOFF 2026-05-17); no DialogCharacter factory yet (Design HANDOFF — quest authored); no Lemmkin Skitter ShipClass in code; no warp-pod entry; no Whirligig in slice-cluster.md yet",
    ),
    (
        "KARAVEM",
        "Karavem / Veled-Of-The-Canyon-Wall (elder conductor) + Pheri-Sings-Open (musical theorist) + Olava-Counterpoint (Aria-Skiff pilot)",
        "full-sentient (winged humanoid musical philosophers; ~1.5m bipedal with large feathered wings; complex throat-organ produces THREE simultaneous notes; ~150-year lifespan; communication is ENTIRELY MUSICAL — they have no spoken language)",
        "precursor (Migrating to Andromeda specifically for the canonical 'better acoustics' of that galaxy's dimensional substrate; partially substantiated by Furling Hider research)",
        "Aeris-Sing (high-altitude terrestrial world with slow 40-hour stellar rotation; cliff-side canyon perch-cities carved into vast acoustically-resonant walls)",
        "Winged philosopher-species whose language IS music. Every utterance is a small composition. Furling translator renders songs as prose-with-musical-annotation; ~30% of nuance is lost. Three regional plumage palettes (western golden-rust, eastern pale-cream-and-sage, highland deep-indigo). The slice's clearest example of *exotic-but-grounded* — they have specific scientific reasons for the Migration (Andromeda acoustic substrate), not just aesthetic preference. Cooperate with Kovellim (who've scouted Andromeda canyon-sites with the right acoustics) and Selvenne (recording reef-memories as musical scores).",
        "references/lore/species-the-karavem.md",
        "TODO_AVATAR: Veled-Of-The-Canyon-Wall (elder, deep-indigo plumage)",
        "karavem_aria_skiff",
        "Karavem Aria-Skiff (light fast bird-of-prey vessel; Harmonic Lance primary + Counterpoint Stitch special that reverses enemy thrust)",
        "TODO Image chat: Welcome Choir portrait + individual Karavem portrait + Aeris-Sing canyon-city backdrop + Aria-Skiff exterior",
        "KARAVEM",
        "yes (optional encounter; quest_id karavem_song_exchange in tools/quest_inventory.csv)",
        "no portrait yet (Image HANDOFF 2026-05-17); no DialogCharacter factory yet (Design HANDOFF — musical-translation dialog rendering); no Karavem Aria-Skiff ShipClass in code; no Aeris-Sing in slice-cluster.md yet",
    ),
    (
        "KOVELLIM",
        "Kovellim / Ovala-Eight-Crossings (elder; will lead Furling Migration's dimensional navigation)",
        "full-sentient (tall ~3-4m bipedal humanoid Migration-veterans; ~1,200-year lifespan; knot-scarred bodies record prior crossings; elders bear seven scars [will gain an eighth in our Migration])",
        "precursor (Stay-Go — the slice's STRONGEST Migration voice; multi-cycle nomadic veterans of SEVEN prior galactic crossings; living empirical proof Migration works)",
        "Eight-Knot Station (deep-space station orbiting a halo of small asteroids in slice cluster; the Kovellim coordination hub for the upcoming crossing)",
        "Multi-cycle nomadic Migrators. The ONLY slice species who has personally migrated before — *seven prior times*. Each dimensional crossing leaves a literal knot-scar on the body. Elders are visibly archaeological. Voice: deep, slow, cyclical. Council-tier dimensional-crossing advisors. They provide crossing-maps, engineering protocols, personnel-rotation schedules, post-arrival crisis planning. Cross-canon with Chenjesu (witnesses) and Selvenne (qualia-replay) — together the three species form the slice's prior-cycle knowledge triumvirate.",
        "references/lore/species-the-kovellim.md",
        "TODO_AVATAR: Ovala-Eight-Crossings (elder; deep-set eyes, eight knot-scars, cycle-cloak with 8-crossing-genealogy embroidery)",
        "kovellim_crossing_frigate",
        "Kovellim Crossing-Frigate (migration-class; Knot-Resonance Beam primary + Cycle-Fold dimensional-blink special)",
        "TODO Image chat: Ovala-Eight-Crossings portrait + Eight-Knot Station exterior + interior receiving-chamber dialog backdrop + Crossing-Frigate exterior",
        "KOVELLIM",
        "yes (optional encounter; quest_id kovellim_crossing_trade in tools/quest_inventory.csv) — they grant THREE crossing-modules in exchange for fresh galaxy-data",
        "no portrait yet (Image HANDOFF 2026-05-17); no DialogCharacter factory yet (Design HANDOFF — quest authored); no Crossing-Frigate ShipClass in code; no Eight-Knot Station in slice-cluster.md yet; the three crossing-modules need Design definition",
    ),
    (
        "DEFENDER_FACTION",
        "Furling Defender / 'We Will Not Run'",
        "Furling-faction",
        "homesteader (Stay; build Sa-Matra)",
        "scattered Furling enclaves",
        "Sub-faction that refuses to flee; builds the Sa-Matra super-weapon; vows to defend Homesteader species' homeworlds. The math is bad (every Defender is one fewer through the portal) but the doctrine is unshakeable.",
        "references/lore/factions-and-war.md §Defenders",
        "—",
        "defender_vessel",
        "Defender Vessel",
        "—",
        "FURLING_DEFENDER",
        "referenced-only (courier passes through in Act 3)",
        "no dialog character; no Firefly portrait",
    ),
    (
        "DEFIANT",
        "(duplicate row — renamed 2026-05-17 to MROKON, see MROKON row)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "MROKON",
        "Mrokon / Vrek-The-Eighth-Body (puppet name; Operator behind it is Vrek, canonically unnamed by tradition)",
        "full-sentient (the slice's DEFIANT species — Operators are ~1m bunker-dwellers; puppets are ~2.3m armored warriors deep-linked from underground; Operator burns through 4-6 puppets per lifetime)",
        "homesteader-by-combat-doctrine (Stay-to-fight; the Hammer-Of-Refusal canonically marks the Others, producing the SC2-era 'dimpled Vessel' anomaly)",
        "Mrokon's Stand (rocky terrestrial world in slice cluster; barren warrior-training grounds on surface; deep Operator bunkers underground)",
        "Warrior-puppet operator species. Each Operator (~1m, child-sized, large skull, bunker-dweller) deep-links to combat puppets (~2.3m armored). Puppets are EXPENDABLE — Operators routinely burn through 4-6 in a lifetime. THE HAMMER-OF-REFUSAL: at the moment of Culling, every Operator fires their last puppet's kinetic-impact round at the Others. The Mrokon are Eliminated, but they MARK the predator. The SC2-era 'Others' Vessel has dimples' observation is canonically the result. Cross-canon: the Mrokon are the ONLY slice species that physically affects the Others.",
        "references/lore/species-the-mrokon.md",
        "TODO_AVATAR: Vrek-The-Eighth-Body (puppet) + an Operator-bunker portrait (rare; only after support-Hammer branch)",
        "mrokon_hammer_ship",
        "Mrokon Hammer-Ship (heavy battleship with Kinetic Cannon primary + Hammer-Round single-use special)",
        "TODO Image chat: Vrek-The-Eighth-Body puppet portrait + Operator bunker portrait + Mrokon's Stand surface + Hammer-Ship exterior",
        "MROKON",
        "yes (optional encounter; quest_id mrokon_hammer in tools/quest_inventory.csv) — slice's defining defiance moment",
        "no portrait yet (Image HANDOFF 2026-05-17); no DialogCharacter factory yet (Design HANDOFF — quest authored); no Mrokon Hammer-Ship ShipClass in code; no warp-pod entry; no Mrokon's Stand in slice-cluster.md yet",
    ),
    (
        "DENIER_FACTION",
        "Furling Denier / 'The Others Are A Story'",
        "Furling-faction",
        "homesteader (philosophical; denies threat)",
        "scattered Furling enclaves + civilian sympathy",
        "Sub-faction that rejects the Others thesis entirely. Believes dimensional ripples are explainable, the Migration is a power-grab. Their propaganda creates Holdouts who then become Cleanser targets — the cruelest irony in the war.",
        "references/lore/factions-and-war.md §Deniers",
        "—",
        "—",
        "—",
        "—",
        "—",
        "referenced-only (Slylandro elder repeats a Denier line in Act 2)",
        "no dialog character, no ship, no Firefly portrait, no warp pod",
    ),
    (
        "DNYARRI_UMGAH_PROTO",
        "Proto-Dnyarri/Umgah",
        "pre-sentient (proto, parasitic)",
        "neither",
        "Orionis area",
        "Parasitic microorganisms that infect hosts and subtly modulate behavior. Not yet sentient themselves; modulation is biological-instinct level. Archive flag: low-priority surveillance.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "DRUUGE_PROTO",
        "Proto-Druuge",
        "pre-sentient (proto)",
        "neither",
        "Caeli region (heat-vent cave systems)",
        "Small mammals; hoard pebbles/bones/mineral fragments; primitive exchange protocols (trade shiny objects for grooming, shelter, mating access). Capitalism in proto-form. Furling archive: 'fascinating proto-economy; we will not interfere.'",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "FURLING_SCOUT",
        "Furling Steward (player) / Commander Halia",
        "full-sentient (player species)",
        "precursor (Persuader-aligned for the player's home cluster)",
        "Mh-Lai (the Hearth)",
        "The player's species. 5-8 meter shaggy mammoth-furred bipeds; slow-breeding; long-lived; value memory above all; gardeners of the galaxy. Steward = player class; Commander Halia is the home-base authority figure.",
        "references/lore/the-furlings-and-the-others.md; species-precursor-era.md",
        "commander_halia",
        "furling_scout",
        "Furling Scout",
        "assets/comm/commander/ (SC2 lift)",
        "FURLING_SCOUT",
        "yes (player + home base)",
        "no Firefly portrait for Halia yet; the Scout ship sprite is procedural-only in code",
    ),
    (
        "HIDER_FACTION",
        "Furling Hider / 'Pockets of Quiet'",
        "Furling-faction",
        "split (cloak-then-migrate / cloak-and-stay)",
        "scattered Furling enclaves",
        "Sub-faction proposing small shielded enclaves instead of full evacuation — single shielded planets, star systems wrapped in dimensional baffling. Some research shared with Arilou (Quasi-Space tech). Untested at scale.",
        "references/lore/factions-and-war.md §Hiders",
        "—",
        "—",
        "—",
        "—",
        "—",
        "referenced-only (Council debate context for Mycon decision)",
        "no dialog character, no ship, no Firefly portrait",
    ),
    (
        "ILWRATH_PROTO",
        "Proto-Ilwrath",
        "pre-sentient (proto)",
        "neither",
        "Tauri region",
        "Arachnids spinning elaborate, celestially-aligned webs; mass-suicide rituals on calendar days; proto-religion already encoded in behavior. Religious-extremism archetype is bone-deep early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "MAEL_NUM",
        "Mael-Num (DISTINCT from Melnorme — separate SC2-canonical species; one-eyed Sentient Milieu founders)",
        "full-sentient (off-screen)",
        "precursor (implied)",
        "off-screen",
        "**Distinct from the Melnorme — separate SC2-canonical species** (Aaron checked 2026-05-17). Future founders of the SC2 Sentient Milieu. One-eyed species already uplifted by Furlings in our era; mentioned in Slylandro gossip but not encountered in slice. SC2-era trans-galactic diplomats.",
        "references/lore/species-precursor-era.md §Background",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog, no homeworld, off-screen only — could be expanded later",
    ),
    (
        "MELNORME",
        "Melnorme / Trade Master Vermilion",
        "full-sentient (composite: gas-cloud + cyclopean pod)",
        "precursor (with Drahn-loyalist schism)",
        "Drahn (yellow dwarf in slice cluster; will be destroyed by Others when holdouts refuse to leave)",
        "Nomadic merchants. Gas-cloud ionization-pattern energy-beings piloting cyclopean orange pods. Trade tech+info for BIO cargo — their secret motive is to map the Others' detection threshold to teach species to sit just below it. Their homeworld Drahn dies during Migration when holdouts refuse to leave.",
        "references/lore/proto-species-observations.md §Melnorme",
        "melnorme",
        "melnorme_trader",
        "Melnorme Trade Pod",
        "assets/generated_drafts/firefly/tier1_portraits/species_melnorme_portrait.png + assets/generated_drafts/firefly/tier1_ships/ship_melnorme_trader.png",
        "MELNORME",
        "yes (any super-giant star; auto-launch dialog)",
        "no dedicated Drahn-system content yet; no Drahn destruction cutscene",
    ),
    (
        "MMRNMHRM",
        "Mmrnmhrm / Sentinel-Defense-Loop-Cohort-Forty-Seven-Theta",
        "non-biological-machine (full sentient)",
        "homesteader (rooted; defend dead world)",
        "Ossuary (industrial planet with First-Makers' ruins)",
        "Self-modifying robots millions of years old. Their organic creators (the First-Makers) were culled by the Others; the robots' primitive expert-system cognition was below threshold, so the Others ignored them. They continue their original directive — defend the homeworld — knowing it's pointless. Stoic, mathematical, melancholy.",
        "references/lore/the-mmrnmhrm-and-chenjesu.md",
        "—",
        "mmrnmhrm_sentinel",
        "Mmrnmhrm Sentinel",
        "assets/generated_drafts/firefly/tier1_portraits/species_mmrnmhrm_portrait.png",
        "MMRNMHRM",
        "optional (Act 2 visit)",
        "no dialog character authored yet; their Archive Excerpt key-item not yet implemented",
    ),
    (
        "MYCON_BIOT",
        "Mycon Biot",
        "infant-sentient (Deep Child awakening)",
        "homesteader by necessity (mycelial; cannot migrate)",
        "Xylos Prime (gas-giant moon; first Mycon deployment 8,000 years ago)",
        "Furling-engineered terraforming biots. Spore-based, designed to be non-sentient ritual workers. But the first Deep Child whispers are emerging in this cluster — they are *waking up*. If awakening completes, they become a new sentient species under the Migration deadline. The Cleanser climax is over their fate.",
        "references/lore/species-precursor-era.md §Mycon",
        "— (non-verbal; LLM-narrated sensory description)",
        "—",
        "— (planetary substrate; no ships)",
        "assets/comm/mycon/ (SC2 lift) + assets/generated_drafts/firefly/tier1_portraits/species_mycon_biot_portrait.png",
        "MYCON_BIOT",
        "yes (active Council decision)",
        "no dedicated DialogCharacter (non-verbal by design); no Deep Child voice prompt yet",
    ),
    (
        "ORZ_RIFTS",
        "Orz / *fingers* (post-slice content; appear LATE in campaign, inspecting Androsynth ruins)",
        "higher-dimensional bleed; the post-slice Orz manifest as 'fingers' through the rifts — the same SC2-era 'Orz' identity",
        "neither (independent; possibly Other-adjacent; distinct lineage)",
        "pocket dimension ('Dimension *' or somewhere adjacent); the Orz arrive THROUGH rifts rather than from a fixed homeworld",
        "**Late-campaign content (canon 2026-05-17)**: the Orz will be properly introduced post-slice, when the Steward investigates the Androsynth refugee homeworld's ruins. The Orz are *already there*, *finding interesting things*. The Androsynth-disappearance/Orz-arrival pairing canonically explains the SC2-era mystery (Androsynth vanish; Orz appear; the Orz have *opinions* about the missing). In the slice itself: Rifts/momentary intrusions of 'Dimension *' into our space — encountered as anomalies; not yet a coherent species in our era's experience. Full Orz lore lives in a future doc; this row is a placeholder pointing forward.",
        "references/lore/species-precursor-era.md §Background",
        "—",
        "—",
        "— (combat threat only, not a vessel)",
        "assets/comm/orz/ (SC2 lift)",
        "—",
        "referenced-only (dimensional sensor ripples)",
        "no homeworld, no ship class, no dialog character — slice treats them as 'mystery' on purpose",
    ),
    (
        "OTHERS",
        "The Others",
        "trans-dimensional predator (non-biological)",
        "neither (extinction-tier antagonist)",
        "beyond 3D manifold",
        "Apex predators. Sense complex cognition at vast distance. Cull intelligence in cycles measured in millions of years. Do not respond to weapons or diplomacy. Dimensional substrate is invulnerable to 3D physics. The slice's antagonist; their Vessel is hijack-only via a special quest.",
        "references/lore/the-furlings-and-the-others.md",
        "—",
        "— (no canonical hijack-only ship class id yet)",
        "Others' Vessel (hijack-only)",
        "—",
        "OTHERS",
        "yes (slice climax threat)",
        "no Others ship class in ships.py yet; no Decursion weapon implementation; non-interactive except in hijack quest (future)",
    ),
    (
        "PERSUADER_FACTION",
        "Furling Persuader / Commander Halia",
        "Furling-faction",
        "precursor (diplomatic lead)",
        "Mh-Lai + most major Furling stations",
        "Sub-faction leading the Migration via diplomacy. Believe every species can be convinced to leave peacefully if given time and respect. Have the moral high ground but are slow. The player's home-faction by default.",
        "references/lore/factions-and-war.md §Persuaders",
        "commander_halia (dual-purpose with FURLING_SCOUT)",
        "persuader_vessel",
        "Persuader Vessel",
        "—",
        "FURLING_PERSUADER",
        "yes (primary slice faction)",
        "no Halia Firefly portrait yet (uses colored disc fallback)",
    ),
    (
        "PKUNK_PROTO",
        "Proto-Pkunk",
        "pre-sentient (proto, same lineage as proto-Yehat)",
        "neither",
        "near proto-Yehat homeworld",
        "Smaller, ground-foraging birds sharing lineage with proto-Yehat; paired-behavior, preening rituals; proto-empathic substrate. Split from Yehat happens ~50k yrs from now.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient observation only)",
    ),
    (
        "PLANAR",
        "(duplicate row — renamed 2026-05-17, see THINN)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "THINN",
        "The Thinn / We-Who-Witness-the-Edge (renamed from 'the Planar' 2026-05-17 per Aaron's pun: literally Thinn, AND they Thought they could stay if they faced sideways)",
        "full-sentient (wholly invented; two-dimensional ribbon-bodies)",
        "homesteader (cannot Migrate — portal would delete their thin projection)",
        "Spire (sub-Neptune in slice cluster; high atmosphere)",
        "Literally two-dimensional. Vertical iridescent ribbon-bodies with ZERO width — invisible edge-on. Speak in collective plural ('we who watch'). Survival plan: align edge-on at the moment of Others' arrival to present zero cross-section. Their ship (Thinn Blade) has a unique Edge-Align front-facing immunity special. **Brain volume: zero** (canon 2026-05-17) — the Thinn are cheerfully, optimistically dumb; they can hold the Doctrine but cannot revise it. They agree with criticisms of their plan AND continue the plan unchanged, no cognitive dissonance. The species has embraced their Furling-translator nickname 'Thinn' as their own — the joke is theirs now, and it's a triple joke: literally thin, they Thought they could stay by facing sideways, AND thin on cognition.",
        "references/lore/species-the-thinn.md",
        "—",
        "— (Thinn Blade spec authored in species-the-thinn.md, not yet in ships.py)",
        "Thinn Blade",
        "assets/generated_drafts/firefly/tier1_portraits/species_planar_blade_portrait.png (Image chat to rename to species_thinn_blade_portrait.png per 2026-05-17 HANDOFF)",
        "—",
        "optional (mid-game encounter)",
        "no dialog character (TODO_AVATAR: Thinn elder, We-Who-Witness-the-Edge); no Thinn Blade ShipClass in code; no warp-pod entry; no encounter system; thinn_edge_align quest authored in tools/quest_inventory.csv",
    ),
    (
        "PROTO_HUMANS",
        "Proto-Humans (Sol III)",
        "pre-sentient (proto, mid-Neolithic)",
        "neither (deliberately not uplifted)",
        "Sol III / Earth",
        "Early hominids. Tool-using, fire-using, bury their dead. Furling archive notes promising trajectory but the Council voted: 'leave them alone, they will be here when the galaxy regrows.' The slice's fanservice 'visit ancestors' beat.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "—",
        "optional fanservice visit",
        "no on-surface art for the Neolithic encampment yet",
    ),
    (
        "PROTO_QOR_AH",
        "Proto-Qor-Ah",
        "infant-sentient (uplift subspecies)",
        "homesteader (purist branch)",
        "tidal-locked moon adjacent to proto-Ur-Quan",
        "Purifying subspecies of the active uplift project. White-yellow when pure, black when 'impure'; self-amputate impurity. PROBABLY ABOVE the Others' detection threshold; more lethal than their Ur-Quan cousins. Hard-coded ritualism.",
        "references/lore/species-precursor-era.md §Proto-Ur-Quan",
        "—",
        "proto_qor_ah",
        "Proto-Qor-Ah Marauder",
        "—",
        "PROTO_QORAH",
        "yes (optional encounter / combat)",
        "no homeworld name; no dialog character (acceptable — non-verbal); no Firefly portrait",
    ),
    (
        "PROTO_SPATHI",
        "Proto-Spathi",
        "pre-sentient (proto)",
        "neither",
        "Spathiwa-equivalent",
        "Burrow-dwelling sluglike creatures. Coordinated fear-response: terror-postures, terror-songs, the art of cowering perfected. The cowardice archetype is bone-deep 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/spathi/ (SC2 lift)",
        "—",
        "optional slice visit",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_SUPOX",
        "Proto-Supox",
        "pre-sentient (proto)",
        "neither",
        "Libris area",
        "Ambulatory rooted-when-resting photosynthetic creatures. Chemical-pollen communication. Pacifists by metabolism. The gentle-botanist archetype already present.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/supox/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_SYREEN",
        "Proto-Syreen",
        "pre-sentient (proto)",
        "neither",
        "Betelgeuse region",
        "Humanoid sea-dwellers with bioluminescent skin; low-frequency vibrational communication; not yet telepathic but resonant cognition (may evolve into it). Long-range coherent communication archetype.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/syreen/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_THRADDASH",
        "Proto-Thraddash",
        "pre-sentient (proto)",
        "neither",
        "Apodis region",
        "Pack-hunting reptilians; learned to deliberately spread wildfires to drive prey; pack-leadership cycles violently each season. Cyclical-civilization-collapse already in their pack dynamics.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/thraddash/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_URQUAN",
        "Proto-Ur-Quan",
        "infant-sentient (uplift subspecies)",
        "split (player decides which path)",
        "tidal-locked moon (Mh-Lai system vicinity)",
        "Active Furling uplift subspecies. Hierarchical, territorial, dominating; speak pheromone-chord language; developing language, weapons, stellar travel. CURRENTLY JUST BELOW the Others' detection threshold — the slice's central uplift-dilemma question.",
        "references/lore/species-precursor-era.md §Proto-Ur-Quan",
        "— (non-verbal — sensory description)",
        "proto_ur_quan",
        "Proto-Ur-Quan Warship",
        "—",
        "PROTO_URQUAN",
        "yes (active Council debate is the slice's moral spine)",
        "no homeworld name; no Firefly portrait; non-verbal LLM voice prompt not yet authored",
    ),
    (
        "PROTO_UTWIG",
        "(duplicate row — Utwig has become sentient; see UTWIG row)",
        "pre-sentient (proto — HISTORICAL; reclassified 2026-05-17)",
        "—",
        "Gorno region (the Utwig homeworld; same as the UTWIG row)",
        "Earlier Steward observations recorded the Utwig as pre-sentient grazers with hyper-developed shame-response face-hiding. They have JUST become sentient in our era (slice timeframe) and are no longer a proto-species. The pre-existing face-hiding biology has become the biological substrate for the mask-and-ceremony doctrine they adopt as cognitive-dampening. The proto-observation is preserved as deep-past context, not a current observation. See UTWIG row for the active slice species.",
        "references/lore/proto-species-observations.md (now historical-context redirect)",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing — kept as reclassification marker (proto → sentient)",
    ),
    (
        "PROTO_VUX",
        "Proto-VUX",
        "pre-sentient (proto)",
        "neither",
        "Luyten region",
        "Tide-pool molluscs with exceptional color vision; mating-selection by precise color-matching; eat anomalously-colored individuals. Xenophobia-from-color-vision archetype 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/vux/ (SC2 lift)",
        "—",
        "optional slice visit",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_YEHAT",
        "Proto-Yehat",
        "pre-sentient (proto)",
        "neither",
        "Serpentis cluster",
        "Large stratospheric raptors; aerial combat behaviors; wing-clack dominance displays. Warrior-honor archetype 250k years early.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/yehat/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "PROTO_ZOQFOTPIK",
        "Proto-Zoq-Fot-Pik",
        "pre-sentient (proto — three species sharing one world)",
        "neither",
        "Tucanae region",
        "Three distinct species on one tropical world — Zoq (tree-dwelling chittering primate-analog), Fot (burrow-dwelling melancholy crustacean), Pik (stone-still meditation-frog). They don't yet cooperate but will eventually form the SC2 triumvirate.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/zoqfotpik/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "SENTRY_DRONE_47T",
        "Sentry Drone 47-Theta (unionizing)",
        "non-biological-machine (singleton, full sentient enough to unionize)",
        "homesteader (labor dispute, comic)",
        "Mh-Lai Station orbit",
        "Furling maintenance drone in a labor dispute. Singleton, comic-absurd register, demands recognition of the Sentry Drones' bargaining unit. Tutorial Beat 6 combat (he goes left-only; the player pickaxes around right).",
        "references/lore/tutorial-arc-implementation.md §Beat 6",
        "sentry_drone_47t",
        "sentry_drone_47t",
        "Sentry Drone 47-Theta (unionized)",
        "—",
        "—",
        "yes (tutorial combat encounter)",
        "no Firefly portrait yet; sprite is procedural-only",
    ),
    (
        "SHOFIXTI_PROTO",
        "Proto-Shofixti",
        "pre-sentient (proto)",
        "neither",
        "Gorno-adjacent",
        "Small mustelid-analog mammals; extraordinarily aggressive territorial defense; throw themselves at much larger predators. Kamikaze-bravery archetype already present.",
        "references/lore/proto-species-observations.md",
        "—",
        "—",
        "—",
        "—",
        "assets/comm/shofixti/ (SC2 lift)",
        "—",
        "no",
        "no ship, no dialog (correctly — pre-sentient)",
    ),
    (
        "SLYLANDRO",
        "Slylandro Observers / Drift-Of-The-Magenta-Cloud-Witness",
        "full-sentient",
        "homesteader (rooted; cloak-and-stay path)",
        "Beta Corvi / Lai-leh = 'slow breath' (upper troposphere of a gas giant)",
        "Semi-transparent atmospheric eddy-sentients. Evolved 80k yrs ago; watched the Precursors for 50k yrs; pacifist; reverent. Cannot migrate (they ARE their gas giant). Viable paths: cloak via the Cloaking Satellite, or Cleanser euthanasia.",
        "references/lore/species-precursor-era.md §Slylandro",
        "slylandro_witness",
        "—",
        "— (rooted to gas giant; no ships of their own)",
        "assets/comm/slylandro/ (SC2 lift)",
        "SLYLANDRO",
        "yes (primary slice species; Cloaking quest is signature)",
        "no Firefly portrait yet; no ships needed (correct)",
    ),
    (
        "TAALO",
        "Taalo / Silicon-Lattice Fragment-Individual (e.g. 'We-Who-Watch-The-Northwest-Bench')",
        "full-sentient (SC2-canonical silicon-based aliens; shield-tragedy reframe 2026-05-17 third pass — terminal Eliminated)",
        "homesteader (cannot leave planet; build anti-Others Shield in slice; Shield fails; consumed by Others)",
        "Taalo's Stone II (the home mountain world) in the Taalo's Stone system, synthetic at (700, 4800) — pinned in slice-cluster.md §12. Home mountain range ~2000 km long, 8-12 km peaks; walks geologically. Ecosystem-tied metabolism — cannot be relocated.",
        "SC2-canonical silicon-based 'rock-like' mobile sentients. The Taalo ARE a single mountain range; individuals are mobile fragments of that range. Mineral-plate bodies (slate-grey, basalt-dark, violet-amber glow when thinking). Lattice-resonance cognition synced to the home mountain's deep substrate. Cannot leave their planet — metabolism depends on specific local ecosystem (silicate-rich groundwater, mantle-deep heat-vents, crustal radiation spectrum); Furlings tried small-scale ecosystem replication for a research fragment, it died in 4 months. NOT below Others' detection threshold despite silicon substrate — their mountain-cognition is too large and coherent (earlier draft framed them parallel to Chenjesu/Mmrnmhrm; that's retracted). ~5,000-year deep Furling friendship; Steward is the 'fourth Steward' to visit this ridge. **In our slice they are building the Taalo Shield** — a planetary-scale anti-Others defensive barrier — knowing it probably won't work, doing the work anyway. *The work is the dignity. The work is the not-despairing.* The Shield does not work; the Others come through it; the Taalo are consumed during the Culling. The inert Shield survives them and is recovered 230kya later by SC2 archaeologists, who discover a side-effect psionic-nullifier property and use it against the Dnyarri (this is the SC2-canonical 'Taalo Shield' artifact — built for the wrong predator, protective against a different one by accident). Slice quest is a side-quest: help with the Shield (better artifact preservation → better SC2 anti-Dnyarri tool → cleaner Talking Pet defeat) or don't (worse) — the Taalo die regardless.",
        "references/lore/species-sheets.md §9; species-quests.md 'The Shield That Will Not Hold'; furling-artifacts-and-callforwards.md 'The Taalo Shield'",
        "—",
        "—",
        "— (the species IS a mountain range; cannot leave the planet; no voidcraft; the Shield is a planetary installation, NOT a vessel)",
        "—",
        "TAALO",
        "yes — side-quest 'The Shield That Will Not Hold'. Multi-visit across the slice. Help with the Shield construction or don't. The Taalo die regardless; the player choice affects how complete the inert SC2-era artifact is. Reward: Hider-faction archive entry + Persuader-faction witnessing entry + Shield-fragment to carry to Andromeda + Taalo standing rises across all factions. The slice's defining tragedy by design.",
        "NEEDS: Firefly portrait for a Taalo fragment-individual (slate-grey mineral-plate body with violet-amber glow patterns syncing across plates; quadrupedal-leaning bipedal stride; two pairs of stride-limbs + two upper articulator-limbs; sensory facets distributed across upper hemisphere with NO concentrated head; geological-patient pose); Firefly landscape for the Taalo home mountain range on Taalo's Stone II (2000km-long range with 8-12km peaks; **Shield-infrastructure embedded in the flanks** — deep-anchored generator-nodes at regular intervals along the range, pale-violet pre-activation glow patterns, Taalo geometer-fragments moving slowly between nodes); Firefly landscape for the contemplation-cove (natural amphitheater in the mountain's flank where Stewards land); **Firefly artifact illustration for the Taalo Shield in its activated state** (mountain-anchored, pale-violet field-projection arcing over the surface, visible from orbit); **Firefly cutscene for the Shield activation + failure + consumption** (slice's defining tragic beat — Shield activates, Others arrive, Shield does nothing, Taalo consumed); **Firefly artifact illustration for the inert post-failure Shield** (this becomes the SC2-era 'Taalo Shield' that archaeologists recover); dialog character for a Witness fragment (one of: We-Who-Watch-The-Northwest-Bench / The-Slow-Watcher-At-The-Trailhead / Mineral-Sampler-Of-The-South-Watershed); lattice-resonance audio (very slow chant-like vocalizations, multi-second pauses, rare mountain-thought interjections with weight-shift in tone)",
    ),
    (
        "TALOS",
        "(duplicate row — retired; the 'Talos' Furling sub-faction is fully retracted; see TAALO and BURVIXESE rows)",
        "—",
        "—",
        "—",
        "Retired 2026-05-17, third pass. Earlier drafts framed 'Talos' as a Furling Stay-Side sub-faction with the Be-Loud doctrine (build a Resonator, broadcast cognition LOUDLY). Both elements have been reassigned: (a) the Taalo are SC2-canonical silicon-based ALIENS (see TAALO row) with no Be-Loud doctrine — they are below threshold by biology; (b) the Be-Loud doctrine and its catastrophic failure belong to the BURVIXESE (see BURVIXESE row), and their device is the Burv Caster, not a Talos Resonator. The Furling factions remain the canonical six: Persuaders, Compellers, Cleansers, Defenders, Deniers, Hiders. No seventh.",
        "(no longer referenced in lore docs)",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing — kept as a sanity-check marker for the Talos retirement",
    ),
    (
        "THE_BARGAINERS",
        "(duplicate row — renamed 2026-05-17 to STELLOTH, see STELLOTH row)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "STELLOTH",
        "Stelloth / Tarvel-Three-Voices (the chord-name; Speaker + Witness + Counter share the designation)",
        "full-sentient (THREE-BODY chord-beings: each Stelloth individual is three coordinated bodies linked by biological cords called murrer; each body operates at a different perceptual timescale — Speaker realtime, Witness 4× fast-motion, Counter 1/10× deep-time)",
        "precursor (Stay-Go — visitor chord-fleet collecting cultural artifacts from endangered slice species before the Culling; Migrating to Andromeda with artifacts)",
        "off-cluster (their chord-vessel orbits a different super-giant from the Melnorme; the Three-Voice Arc trading post; canonical Stelloth Beacon distinguishes them from Melnorme ionization)",
        "Three-body mantis-stack beings; tall ~1.8m per body; jointed exoskeleton; twelve manipulator-limbs total; braided biological cords (murrer) link the bodies. Bodies specialize: Speaker (talks), Witness (records via head-crystal at fast-motion perception), Counter (calculates ramifications at deep-time, clicks shells on its abdomen). A Stelloth CANNOT CONTRACT unless all three are aligned — chord-fragments go catatonic. Trade artifacts (Lemmkin archives, Burvixese recordings, Utwig pre-doctrine voice samples, Taalo shield-fragments, etc.) for rare resources + Counter-predicted deep-time information. The visit complements the Melnorme — sensors at Melnorme, artifacts at Stelloth.",
        "references/lore/species-the-stelloth.md",
        "TODO_AVATAR: Tarvel-Three-Voices (chord; render all three bodies in one frame with the murrer cords + ledger-marks on Counter's carapace)",
        "stelloth_three_voice_arc",
        "Three-Voice Arc (trader vessel; medium combat capability; Contract-Resonance Lance primary + Chord-Witness Scanner special)",
        "TODO Image chat: chord portrait + Three-Voice Arc exterior + their super-giant trading post backdrop",
        "STELLOTH",
        "yes (optional artifact-trade encounter; quest_id stelloth_artifact_trade in tools/quest_inventory.csv) — Witness will sense any artifact the Steward conceals",
        "no portrait yet (Image HANDOFF 2026-05-17); no DialogCharacter factory yet (chord-NPC factory is unusual — Design will need to handle three-voice dialog rendering); no Three-Voice Arc ShipClass in code; no Stelloth Beacon system in slice-cluster.md yet",
    ),
    (
        "THE_DEFIANT_BACKLOG",
        "(duplicate row — concept replaced 2026-05-17 by MROKON, see MROKON row)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "THE_LONG_MEMORIES",
        "(duplicate row — renamed 2026-05-17 to SELVENNE, see SELVENNE row)",
        "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—", "—",
    ),
    (
        "SELVENNE",
        "Selvenne / Choir-Of-The-East-Reef (the host reef-section the Steward dialogs with; name applies to the collective)",
        "full-sentient (PLANET-SCALE coral hive-mind; the species IS a single reef covering ~38% of the Vellumar seabed; each ~5cm polyp holds ~1 year of EXPERIENTIAL memory; reef-wide continuous self-memory back ~50 MILLION years)",
        "precursor (Stay-Go — Migrating to Andromeda; logistically the largest operation in the Migration timetable as Furlings physically lift reef-sections in shielded water-tanks)",
        "Vellumar (ocean world in slice cluster; the Steward visits in a Furling-loaned submarine)",
        "Planet-scale coral reef + experiential memory archive. Each polyp ~5cm; bioluminescent in slow chromatic waves at night. **Exotic canon**: touching a polyp DIRECTLY TRANSMITS a few seconds of an ancient species's QUALIA into the toucher's nervous system — not data, EXPERIENCE. The Steward can LIVE a prior-cycle Slylandro's near-extinction moment, a previous Furling Migration's collapse, etc. The Selvenne archive emotional textures the Hider faction's data-archive misses. Cross-canon with Chenjesu (Chenjesu remember as witnesses; Selvenne remember as participants).",
        "references/lore/species-the-selvenne.md",
        "TODO_AVATAR: Choir-Of-The-East-Reef (collective dialog character; renders as layered chord of many voices)",
        "—",
        "— (sessile coral; no voidcraft; transported by Furling migration vessels)",
        "TODO Image chat: Brain-Coral Sanctum backdrop + individual polyp portrait + memory-playback cinematic frame style",
        "—",
        "yes (optional encounter; quest_id selvenne_memory_archive in tools/quest_inventory.csv) — Steward contributes experiences AND receives memory-playback of ancient species in first person",
        "no Selvenne dialog character yet (chorus-rendering needed); Vellumar not yet in slice-cluster.md; memory-playback cinematic system not yet wired (Design backlog — could reuse Distress Beacon cinematic infrastructure)",
    ),
    (
        "THRADDASH_PROTO",
        "(duplicate row — see PROTO_THRADDASH)",
        "—",
        "—",
        "—",
        "deduped intentionally — single canonical row above as PROTO_THRADDASH",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing — kept as sanity-check marker",
    ),
    (
        "UTWIG",
        "Utwig / Vell-Of-The-Open-Face (pre-doctrine youth) + Korm-Of-The-Folded-Veil (post-doctrine masked elder)",
        "full-sentient (newly-emerged; slice species — Authored 2026-05-17)",
        "homesteader (devolution-by-ceremony; the Veils Falling)",
        "Gorno region (Utwig system; in stars.json at line 79; tagged UTWIG_PROTO in starmap)",
        "JUST became sentient in our era. Armored bipedal humanoids ~1.6m tall with expressive faces (pre-mask) and pre-existing biological face-hiding shame response. On discovering through Furling-assisted measurement that their cognition flares to the Others, they choose the Veils Falling doctrine: mass-adoption of mask-and-ceremony as cognitive-dampening culture. SC2-canonical mask philosophy ('the face is the mechanism that expresses many of the primitive qualities that hinder sentience') preserved — but the *underlying mechanism* is cognitive-pattern flattening below the Others' threshold. The doctrine works: terminal Pre-sentient by chosen culture; they survive the Culling locked into ritual. SC2-era depressed mask-wearers are their descendants. The Ultron is the pre-doctrine Utwig's self-built future-restoration tool, sealed before devolution, found by Druuge 250kyr later. SC3's 'Precursors devolved into animals' is canonically a misreading of THIS story.",
        "references/lore/species-sheets.md §11; species-quests.md 'The Veils Falling'; furling-artifacts-and-callforwards.md 'The Utwig and the Ultron'",
        "—",
        "—",
        "— (technology declared profane by doctrine; pre-doctrine Utwig had simple orbital transfer-shuttles, all dismantled before the Veils Falling. SC2-era Jugger ship is a 250kyr-later Druuge-traded rebuild, not slice-relevant)",
        "assets/comm/utwig/ (SC2 lift; usable for both pre-mask and masked-elder portraits)",
        "UTWIG",
        "yes (mid-game witnessing beat — the Veils Falling ceremony; Steward attends + witnesses, advocates against, or sabotages under Cleanser pressure)",
        "NEEDS: Firefly portrait for unmasked pre-doctrine Utwig (visible expressive face, anguished); Firefly portrait for masked elder devotee (early ceremonial veil); dialog character for both; cinematic for the Veils Falling ceremony (cognitive-signature flare visualization). Utwig-pre-doctrine and Utwig-masked-elder should ship as TWO separate portrait targets to show the cultural transition mid-slice.",
    ),
    (
        "VUX_PROTO",
        "(duplicate row — see PROTO_VUX)",
        "—",
        "—",
        "—",
        "deduped intentionally",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "—",
        "delete this row when importing",
    ),
]


def main() -> int:
    # Default to writing the CSV file directly so we don't depend on the
    # shell's stdout encoding (Windows defaults to CP1252 which corrupts
    # em-dashes). Pass --stdout to emit to stdout instead.
    import io
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true",
                        help="emit to stdout (UTF-8 reconfigured) instead of file")
    parser.add_argument("-o", "--output", default="tools/species_inventory.csv")
    args = parser.parse_args()

    if args.stdout:
        sys.stdout.reconfigure(encoding="utf-8")
        out = sys.stdout
        close_after = False
    else:
        out = open(args.output, "w", encoding="utf-8", newline="")
        close_after = True

    writer = csv.writer(out, lineterminator="\n", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(COLUMNS)
    for row in ROWS:
        if row[1].startswith("(duplicate row"):
            continue
        writer.writerow(row)
    if close_after:
        out.close()
        print(f"wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
